{
 "title": "Allure Metrics",
 "tags": [ "Allure" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "dbinstanceidentifier",
    "query": "dimension_values(eu-west-1, AWS/RDS, CPUUtilization, DBInstanceIdentifier)"
   },
   {
    "name": "metric_filter",
    "query": "service=~\"allure.*\",service=\"allure-testops-report\",service=\"allure-testops-gateway\",service=\"allure-testops-uaa\",service=\"allure-testops-rabbitmq\",service=\"allure-testops-redis-headless\",service=\"allure-testops-rabbitmq-headless\",service=\"allure-testops-redis-master\""
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(jvm_gc_pause_seconds_sum{${metric_filter:raw}}, service)"
    }
   },
   {
    "name": "command",
    "query": {
     "query": "label_values(lettuce_command_firstresponse_seconds_bucket{${metric_filter:raw}}, command)"
    }
   },
   { "name": "diff_interval", "query": "1h, 3h, 6h, 12h, 24h, 2d" }
  ]
 },
 "panels": [
  {
   "title": "${service}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "service",
   "collapsed": true,
   "panels": [
    {
     "title": "firstresponse ${command} - ${service}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 1 },
     "repeat": "command",
     "targets": [
      {
       "expr": "sum(increase(lettuce_command_firstresponse_seconds_bucket{command=\"$command\", service=\"$service\"}[$diff_interval])) by (le)"
      }
     ]
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Incoming RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{job=\"allure-testops-gateway\",uri!~\"/management/.*\",uri!~\"/.well-known/.*\"}[10m]))",
     "legendFormat": "Traffic"
    }
   ]
  },
  {
   "title": "Ram Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"allure-testops-gateway\"})",
     "legendFormat": "Gateway"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"allure-testops-uaa\"})",
     "legendFormat": "UAA"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"allure-testops-report\"})",
     "legendFormat": "Report"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"rabbitmq\"})",
     "legendFormat": "RabbitMQ"
    }
   ]
  },
  {
   "title": "CPU Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"allure-testops-gateway\"}[$__rate_interval]))",
     "legendFormat": "Gateway"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"allure-testops-uaa\"}[$__rate_interval]))",
     "legendFormat": "UAA"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"allure-testops-report\"}[$__rate_interval]))",
     "legendFormat": "Report"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"rabbitmq\"}[$__rate_interval]))",
     "legendFormat": "RabbitMQ"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(idelta(kube_pod_container_status_restarts_total{container=~\"allure-testops.*\"}[$__interval])>0) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "idelta(kube_pod_container_status_restarts_total{container=~\"allure-testops.*\"}[$__interval])>0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go to kibana logs",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "<p>\n  <a target=\"_blank\"\n  href=\"https://logs.eu-west-1.testmiro.com/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'${__from:date}',to:'${__to:date}'))&_a=(columns:!(message,level),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'7bf57d60-33c3-11ef-bf28-1d425afaaa8b',key:kubernetes.container_name,negate:!f,params:(query:allure-testops-report),type:phrase),query:(match_phrase:(kubernetes.container_name:allure-testops-report)))),index:'7bf57d60-33c3-11ef-bf28-1d425afaaa8b',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',asc)))\"\n  >allure-report-logs</a>\n</p>\n"
   }
  },
  {
   "title": "MQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      { "expr": "rabbitmq_queue_consumers", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "Total Messages in Queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "irate(rabbitmq_queue_messages{queue_name=~\"\"}[10m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "jvm_memory_committed_bytes +  jvm_memory_max_bytes($service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(jvm_memory_committed_bytes{service=\"$service\"}[$__rate_interval]) by (area)",
     "legendFormat": "committed {{area}}"
    },
    {
     "expr": "max(jvm_memory_max_bytes{service=\"$service\"}[$__rate_interval]) by (area)",
     "legendFormat": "max {{area}}"
    }
   ]
  },
  {
   "title": "jvm_memory_committed_bytes ($service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(sum(jvm_memory_committed_bytes{service=\"$service\"}[$__rate_interval]) by (pod))",
     "legendFormat": "avg"
    },
    {
     "expr": "max(sum(jvm_memory_committed_bytes{service=\"$service\"}[$__rate_interval]) by (pod))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "jvm_memory_committed_bytes ($service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{service=\"$service\"}[$__rate_interval]) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "jvm_memory_committed_bytes ($service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_committed_bytes{service=\"$service\"}[$__rate_interval]) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "jvm_threads ($service) - sum",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 89 },
   "repeat": "service",
   "targets": [
    {
     "expr": "sum(jvm_threads_states_threads{service=\"$service\"}[$__rate_interval]) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "jvm_threads ($service) - avg",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "avg(jvm_threads_states_threads{service=\"$service\"}[$__rate_interval]) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "executor_active_threads ($service) - sum",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 115 },
   "repeat": "service",
   "targets": [
    {
     "expr": "sum(executor_active_threads{service=\"$service\"}[$__rate_interval]) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "executor_active_threads ($service) - avg",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "avg(executor_active_threads{service=\"$service\"}[$__rate_interval]) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "executor_pool_core_threads ($service) - sum",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 135 },
   "repeat": "service",
   "targets": [
    {
     "expr": "sum(executor_pool_core_threads{service=\"$service\"}[$__rate_interval]) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "executor_pool_core_threads ($service) - avg",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 145 },
   "targets": [
    {
     "expr": "avg(executor_pool_core_threads{service=\"$service\"}[$__rate_interval]) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics (count)",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      { "expr": "{${metric_filter:raw}}" }
     ]
    },
    {
     "title": "Service (count)",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "targets": [
      { "expr": "{${metric_filter:raw}}" }
     ]
    },
    {
     "title": "Metrics (count) - lettuce_command",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"lettuce_command.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - http_server_requests_seconds",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"http_server_requests_seconds.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - erlang",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"erlang.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - jvm",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"jvm.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - logback_events_total",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"logback_events_total.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - executor",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"executor.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - jdbc",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"jdbc.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - spring",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"spring.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - hikaricp",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"hikaricp.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - allure",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"allure.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - application",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"application.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - disk",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"disk.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - process",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"process.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - rabbitmq",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 124 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"rabbitmq.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - scrape",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "{service=\"allure-testops-report\",__name__=~\"scrape.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - system",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 140 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"system.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - tomcat",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 148 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"tomcat.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - up|count",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 156 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"up.*|count.*\"}"
      }
     ]
    },
    {
     "title": "Metrics (count) - kube",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 164 },
     "targets": [
      {
       "expr": "{${metric_filter:raw},__name__=~\"kube.*\"}"
      }
     ]
    }
   ]
  }
 ]
}