{
 "title": "Allure S3 dashboard",
 "tags": [ "Allure" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "cloudwatch" },
   { "name": "region", "query": "regions()" },
   {
    "name": "bucket",
    "query": "dimension_values($region,AWS/S3,NumberOfObjects,BucketName)"
   }
  ]
 },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of 4xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket", "FilterId": "*" },
     "metricName": "4xxErrors",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Number of 5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket", "FilterId": "*" },
     "metricName": "5xxErrors",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Get Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket", "FilterId": "*" },
     "metricName": "GetRequests",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Delete Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket", "FilterId": "*" },
     "metricName": "DeleteRequests",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Put Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket", "FilterId": "*" },
     "metricName": "PutRequests",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Head Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket", "FilterId": "*" },
     "metricName": "HeadRequests",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Gigabytes Uploaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket", "FilterId": "*" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Gigabytes Downloaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket", "FilterId": "*" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Bucket Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Number of Objects (Millions)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket", "StorageType": "*" },
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Bucket Size (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket", "StorageType": "*" },
     "metricName": "BucketSizeBytes",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}