{
 "title": "Allure RDS dasboard",
 "description": "Visualize AWS RDS metrics",
 "tags": [ "Allure" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "rdsdatasource", "query": "cloudwatch" },
   { "name": "rdsregion", "query": "regions()" },
   {
    "name": "dbinstanceidentifier",
    "query": "dimension_values($rdsregion, AWS/RDS, CPUUtilization, DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPUUtilization/FailedSQLServerAgentJobsCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "$rdsregion",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "FailedSQLServerAgentJobsCount",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "$rdsregion",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DatabaseConnections/DiskQueueDepth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "region": "$rdsregion",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "region": "$rdsregion",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "FreeableMemory/FreeStorageSpace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "region": "$rdsregion",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "region": "$rdsregion",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read/Write Operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "ReadIOPS/WriteIOPS/BurstBalance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "metricName": "ReadIOPS",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Average"
      },
      {
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "metricName": "WriteIOPS",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Average"
      },
      {
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "metricName": "BurstBalance",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "ReadLatency/WriteLatency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "metricName": "ReadLatency",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Average"
      },
      {
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "metricName": "WriteLatency",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "ReadThroughput/WriteThroughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "apiMode": "Metrics",
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "metricName": "ReadThroughput",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Average"
      },
      {
       "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
       "metricName": "WriteThroughput",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "NetworkReceiveThroughput/NetworkTransmitThroughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "region": "$rdsregion",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "region": "$rdsregion",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SwapUsage/BinLogDiskUsage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "SwapUsage",
     "namespace": "AWS/RDS",
     "region": "$rdsregion",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReplicationSlotDiskUsage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "ReplicationSlotDiskUsage",
     "namespace": "AWS/RDS",
     "region": "$rdsregion",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "MaximumUsedTransactionIDs/TransactionLogsGeneration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "MaximumUsedTransactionIDs",
     "namespace": "AWS/RDS",
     "region": "$rdsregion",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "TransactionLogsGeneration",
     "namespace": "AWS/RDS",
     "region": "$rdsregion",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "ClientConnections",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "connections" }
     ],
     "targets": [
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "ClientConnectionsReceived",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Sum"
      },
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "ClientConnections",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Sum"
      },
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "ClientConnectionsClosed",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Sum"
      },
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "ClientConnectionsSetupFailedAuth",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Max database connection allowed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "connections" }
     ],
     "targets": [
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "MaxDatabaseConnectionsAllowed",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Database connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "connections" }
     ],
     "targets": [
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "DatabaseConnectionRequests",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Sum"
      },
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "DatabaseConnections",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Sum"
      },
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "DatabaseConnectionsCurrentlyInTransaction",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Sum"
      },
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "DatabaseConnectionsCurrentlySessionPinned",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Sum"
      },
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "DatabaseConnectionsSetupFailed",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Database connections borrow",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "connections" }
     ],
     "targets": [
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "DatabaseConnectionsBorrowLatency",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Sum"
      },
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "DatabaseConnectionsCurrentlyBorrowed",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Queries Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "connections" }
     ],
     "targets": [
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "QueryRequests",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Queries Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "connections" }
     ],
     "targets": [
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "QueryDatabaseResponseLatency",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Average"
      },
      {
       "dimensions": { "ProxyName": "$proxy" },
       "metricName": "QueryResponseLatency",
       "namespace": "AWS/RDS",
       "region": "$rdsregion",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Documentation",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 42 },
     "options": {
      "content": "<a style=\"xfloat: right\" href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a style=\"xfloat: left\"  target=\"_blank\" href=\"https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MonitoringOverview.html#monitoring-cloudwatch\">AWS CloudWatch RDS documentation</a> | \n<a style=\"xfloat: left\"  target=\"_blank\" href=\"https://grafana.com/dashboards/707\">Installed from Grafana.com dashboards</a>"
     }
    }
   ]
  }
 ]
}