{
 "title": "HikariCP allure",
 "tags": [ "Allure" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(hikaricp_connections_max{namespace=\"qa-automation\"}, service)"
    }
   },
   { "name": "source", "label": "Environment", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{pod_ip!=\"\", pod=~\"$service-.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{service=\"$service\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(hikaricp_connections_idle{service=\"$service\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(hikaricp_connections_max{service=\"$service\"})",
     "legendFormat": "Maximum available"
    }
   ]
  },
  {
   "title": "Available connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_idle{service=\"$service\"})\n/ \nsum(hikaricp_connections_max{service=\"$service\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Time (avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  rate(hikaricp_connections_usage_seconds_sum{service=\"$service\"}[$__rate_interval])\n  /\n  rate(hikaricp_connections_usage_seconds_count{service=\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(\n  rate(hikaricp_connections_creation_seconds_sum{service=\"$service\"}[$__rate_interval])\n  /\n  rate(hikaricp_connections_creation_seconds_count{service=\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "Creation"
    },
    {
     "expr": "avg(\n  rate(hikaricp_connections_acquire_seconds_sum{service=\"$service\"}[$__rate_interval])\n  /\n  rate(hikaricp_connections_acquire_seconds_count{service=\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "Acquire"
    }
   ]
  },
  {
   "title": "Time (max)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(hikaricp_connections_usage_seconds_max{service=\"$service\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(hikaricp_connections_creation_seconds_max{service=\"$service\"})",
     "legendFormat": "Creation"
    },
    {
     "expr": "max(hikaricp_connections_acquire_seconds_max{service=\"$service\"})",
     "legendFormat": "Acquire"
    }
   ]
  },
  {
   "title": "Threads waiting for connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pool) (hikaricp_connections_pending{service=\"$service\"})",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Time (sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(idelta(hikaricp_connections_usage_seconds_sum{service=\"$service\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time (sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(idelta(hikaricp_connections_usage_seconds_sum{service=\"$service\"}[$__rate_interval])) by (pool)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }, "repeat": "pod" },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (pool) (hikaricp_connections_active{service=\"$service\", pod=\"$pod\"})",
     "legendFormat": "Active {{pool}}"
    },
    {
     "expr": "max by (pool) (hikaricp_connections_max{service=\"$service\", pod=\"$pod\"})",
     "legendFormat": "Maximum available {{pool}}"
    }
   ]
  },
  {
   "title": "Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum(rate(hikaricp_connections_usage_seconds_sum{service=\"$service\", pod=\"$pod\"}[$__rate_interval])) by (pool)\n/\nsum(rate(hikaricp_connections_usage_seconds_count{service=\"$service\", pod=\"$pod\"}[$__rate_interval])) by (pool)",
     "legendFormat": "Usage {{pool}}"
    },
    {
     "expr": "sum(rate(hikaricp_connections_creation_seconds_sum{service=\"$service\", pod=\"$pod\"}[$__rate_interval])) by (pool)\n/\nsum(rate(hikaricp_connections_creation_seconds_count{service=\"$service\", pod=\"$pod\"}[$__rate_interval])) by (pool)",
     "legendFormat": "Creation {{pool}}"
    },
    {
     "expr": "sum(rate(hikaricp_connections_acquire_seconds_sum{service=\"$service\", pod=\"$pod\"}[$__rate_interval])) by (pool)\n/\nsum(rate(hikaricp_connections_acquire_seconds_count{service=\"$service\", pod=\"$pod\"}[$__rate_interval])) by (pool)",
     "legendFormat": "Acquire {{pool}}"
    }
   ]
  },
  {
   "title": "Available connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pool) (\nhikaricp_connections_idle{service=\"$service\", pod=\"$pod\"}\n/\nhikaricp_connections_max{service=\"$service\", pod=\"$pod\"})",
     "legendFormat": " {{pool}}"
    }
   ]
  },
  {
   "title": "Threads waiting for connection",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (pool) (hikaricp_connections_pending{service=\"$service\", pod=\"$pod\"})",
     "legendFormat": "Threads {{pool}}"
    }
   ]
  }
 ]
}