{
 "title": "RDS PostgreSQL metrics -- Allure TestOps",
 "time": { "from": "now-20d", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "prometheus", "query": "prometheus" },
   { "name": "cloudwatch", "label": "cloudwatch", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(pg_up{namespace!=\"\"}, miro_region)"
    }
   },
   {
    "name": "RDS_name",
    "label": "rds_deployment",
    "query": {
     "query": "label_values(pg_up{namespace!=\"\"}, miro_rds_cluster)"
    }
   },
   {
    "name": "RDS",
    "label": "rds_instance",
    "query": "dimension_values($region, AWS/RDS, CPUUtilization, DBInstanceIdentifier)"
   },
   {
    "name": "RDS_Proxy",
    "label": "rds_proxy",
    "query": "dimension_values($region, AWS/RDS, AvailabilityPercentage ,ProxyName)"
   },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "label_values(pg_stat_database_xact_commit{miro_rds_cluster=\"$RDS_name\",datname!~\"(postgres|rdsadmin|template0|template1)\",namespace=\"observability-exporters\"}, datname)"
    }
   },
   {
    "name": "rds_instance_resource_id",
    "label": "rds_instance_resource_id",
    "query": {
     "query": "label_values(pg_up{namespace!=\"\",miro_rds_cluster=\"$RDS_name\"}, miro_rds_instance_resource_id)"
    }
   },
   {
    "name": "rds_url",
    "label": "rds_url",
    "query": {
     "query": "label_values(pg_stat_database_xact_commit{miro_rds_cluster=\"$RDS_name\"},server)"
    }
   },
   { "name": "1", "query": "$$1" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum_over_time(sum(increase(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}[$__range]\n)) by (queryid))",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Queries (templates)",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3934084821068338370|-7629315488505523782|-9118850505870576616|-1407348636818196047|5343797223471241302|-1724946079165604596|-3314170056428998073|-5599554464466329331\"}[$__interval],\n\"query_key\", 'with \"tr_lk\" as (select \"test_result\".\"id\" from \"test_result\" where (\"test_result\".\"launch_id\" = $$1 and \"test_result\".\"history_key\" IN KEYS) order by \"test_result\".\"id\" for no key update), \"tr_rt\" as (select \"test_result\".\"id\", first_value(\"test_result\".\"id\") over (partition by \"test_result\".\"history_key\" order by coalesce(\"test_result\".\"start\", \"test_result\".\"stop\", \"test_result\".\"created_date\") desc nulls last) as \"tr1\" from \"tr_lk\" join \"test_result\" on \"test_result\".\"id\" = \"tr_lk\".\"id\" order by \"test_result\".\"id\") update \"test_result\" set \"hidden\" = (\"test_result\".\"id\" <> \"tr_rt\".\"tr1\"), \"retried_by\" = case when \"test_result\".\"id\" <> \"tr_rt\".\"tr1\" then \"tr_rt\".\"tr1\" else cast($$1 as bigint) end, \"last_modified_by\" = $$1, \"last_modified_date\" = $$1 from \"tr_rt\" where \"test_result\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-1890520225001541202|8541189628386284755|-6729167206932895045|-4956885308137481126|-7851074193500501429|8309675949422813515|-2562509008144719696|5387232704629596238|-5557594060599571491\"}[$__interval],\n\"query_key\", 'update \"test_result\" set \"full_name\" = \"v\".\"c1\", \"description\" = \"v\".\"c1\", \"description_html\" = \"v\".\"c1\", \"precondition\" = \"v\".\"c1\", \"precondition_html\" = \"v\".\"c1\", \"expected_result\" = \"v\".\"c1\", \"expected_result_html\" = \"v\".\"c1\", \"test_layer_id\" = cast(\"v\".\"c1\" as bigint), \"manual\" = \"v\".\"c1\", \"status\" = \"v\".\"c1\", \"message\" = \"v\".\"c1\", \"trace\" = \"v\".\"c1\", \"start\" = cast(\"v\".\"c1\" as bigint), \"stop\" = cast(\"v\".\"c1\" as bigint), \"duration\" = cast(\"v\".\"c1\" as bigint), \"host_id\" = \"v\".\"c1\", \"thread_id\" = \"v\".\"c1\", \"local_run_uuid\" = \"v\".\"c1\" from (VALUES (VAL)) where \"test_result\".\"id\" = \"v\".\"c1\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"5440757910167813368|-2754656615418654773|4447347532761596015|-4985950084870127777|4066338591555528632|2783677633027607696|3306178492070608084|3224420977893184079\"}[$__interval],\n\"query_key\", 'insert into \"test_result_scenario_block\" (\"test_result_id\", \"data\", \"created_by\", \"created_date\", \"last_modified_by\", \"last_modified_date\") select \"v\".\"c1\", \"v\".\"c1\", $$1, $$1, $$1, $$1 from (VALUES (VAL)) do update set \"data\" = \"excluded\".\"data\", \"last_modified_by\" = $$1, \"last_modified_date\" = $$1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"354776470543819834|-2013418728145581168|-5941973755437388416|-1138148854663917314|-6151010435157117400|1504231528310994426|6771795209721327702|8264927604351288767|1031709803157834306\"}[$__interval],\n\"query_key\", 'insert into \"test_result\" (\"launch_id\", \"test_session_id\", \"job_run_id\", \"id\", \"test_case_id\", \"name\", \"history_key\", \"hidden\", \"external\", \"created_by\", \"created_date\", \"last_modified_by\", \"last_modified_date\") VALUES (VAL) do update set \"launch_id\" = \"excluded\".\"launch_id\", \"test_session_id\" = \"excluded\".\"test_session_id\", \"job_run_id\" = \"excluded\".\"job_run_id\", \"test_case_id\" = \"excluded\".\"test_case_id\", \"name\" = \"excluded\".\"name\", \"history_key\" = \"excluded\".\"history_key\", \"hidden\" = $$1, \"external\" = $$1, \"last_modified_by\" = $$1, \"last_modified_date\" = $$1 returning \"test_result\".\"id\", \"test_result\".\"test_case_id\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"6973423874184579389|1931361531336001837|6134564063525871934|892735712321394778|-6454084909132048456|-6267104841689983545|800169189322848841|1835519071896069564|-5670520736262774960|7289690819468492297|-719898416793592636|-3171469207843903637|6656928851985625580|-4532199773036126758|5246163688087098552|7856500316668066297\"}[$__interval],\n\"query_key\", 'insert into \"test_result_custom_field\" (\"test_result_id\", \"custom_field_value_id\") select \"v\".\"c1\", \"v\".\"c1\" from (VALUES (VAL)) do nothing', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-5961531816685115219|5348561853148171200|-2024315525205880296|-3946352109319617114|-7114134203024639928|3857573856810294698|4696212443935485341|3243486293748510443\"}[$__interval],\n\"query_key\", 'update \"test_result\" set \"scenario_key\" = $$1, \"last_modified_by\" = $$1, \"last_modified_date\" = $$1 where \"test_result\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"1157584214810043055\"}[$__interval],\n\"query_key\", 'update \"launch\" set \"last_modified_date\" = $$1, \"last_modified_by\" = $$1 where \"launch\".\"id\" = $$1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-1416140981673074347\"}[$__interval],\n\"query_key\", 'select distinct \"test_result\".\"id\", \"test_result\".\"name\", \"test_result\".\"status\", \"test_result\".\"start\", \"test_result\".\"stop\", \"test_result\".\"duration\", \"test_result\".\"manual\", \"test_result\".\"assignee\", \"test_result\".\"tested_by\", \"test_result\".\"test_case_id\", \"test_layer\".\"name\", -(\"test_result\".\"status\") from \"test_result\" left outer join \"test_layer\" on \"test_result\".\"test_layer_id\" = \"test_layer\".\"id\" where (\"test_result\".\"launch_id\" = $$1 and \"test_result\".\"hidden\" = $$1 and $$1) order by \"test_result\".\"test_case_id\" asc limit $$1 offset $$1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3065101627323191925|6172012046876450672|-154770314165353031|-4713854124755418034|-5345628697385564956|-4444445086239616450|8288715177846116362|-5728658692971845333|4285799337526335392\"}[$__interval],\n\"query_key\", 'with \"exp_tr1\" as (select distinct on (\"v\".\"c1\") \"v\".\"c1\", \"test_result\".\"id\" from \"test_result\" join (VALUES (VAL)) select \"exp_tr1\".\"c1\", \"test_result\".\"id\" from \"test_result\" join \"exp_tr1\" on \"test_result\".\"id\" = \"exp_tr1\".\"id\" order by \"test_result\".\"id\" for no key update skip locked', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-8946200807776987162|-9200057509331791363|-8063467946522176185|435219297541885788|-3665261003842485834|8252378364890499554|-5024892381980960465\"}[$__interval],\n\"query_key\", 'select bool_and(exists (with \"up_cte\" as (((select distinct \"permission_permission_set\".\"permission\" from \"group_project_access\" join \"access_group\" on \"group_project_access\".\"group_id\" = \"access_group\".\"id\" join \"group_user\" on \"group_user\".\"group_id\" = \"access_group\".\"id\" join \"permission_permission_set\" on \"permission_permission_set\".\"permission_set_id\" = \"group_project_access\".\"permission_set_id\" where (\"group_project_access\".\"project_id\" = \"project\".\"id\" and \"group_user\".\"username\" = $$1 and (\"access_group\".\"personal\" = $$1 or (\"access_group\".\"personal\" = $$1 and \"access_group\".\"name\" = $$1)))) union all (select \"v\".\"c1\" from (VALUES (VAL)) from \"project\" where \"project\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-81176439872564081|17670673547066367|1545784804722760381|-4488997511127977649|3958803941604940321|-3950490104272315063|-9174957291846684074|2956845977626877848|2624756295929383646|-4864816528718272866\"}[$__interval],\n\"query_key\", 'delete from \"result_file_key\" where \"result_file_key\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-4459481342769312776\"}[$__interval],\n\"query_key\", 'select count(*) from \"test_result\" where (\"test_result\".\"launch_id\" = $$1 and \"test_result\".\"hidden\" = $$1 and $$1)', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-2077094910282544909\"}[$__interval],\n\"query_key\", 'insert into blob_remove_task (storage_key) VALUES (VAL) on conflict do nothing', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"3415057726328186314|118716905370055968|6054185593216042258|-4682194556151941318|-2764246633192238751|-1294727602406559514|-6336725022792132409|-7287447943429565885|1103572228662402772|3327111597703155155|8341980863677065211\"}[$__interval],\n\"query_key\", 'insert into \"test_result_environment\" (\"test_result_id\", \"env_var_value_id\") select \"v\".\"c1\", \"v\".\"c1\" from (VALUES (VAL)) do nothing', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"8985625205764313059\"}[$__interval],\n\"query_key\", 'select \"test_result\".\"status\", count(\"test_result\") from \"test_result\" where (\"test_result\".\"launch_id\" = $$1 and \"test_result\".\"muted\" = $$1 and \"test_result\".\"hidden\" = $$1) group by \"test_result\".\"status\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-5352755801224380671|-7232752617337134793|2126783132189623321|-6011106520953329790|8360599381691416625|-5387688731442853877|4373750156909557718|7294443988928756034|3027496910096275572|-7626796848630585055\"}[$__interval],\n\"query_key\", 'insert into \"result_file_key\" (\"test_session_id\", \"original_file_name\", \"storage_key\", \"content_type\", \"content_length\") select $$1, \"v\".\"c1\", \"v\".\"c1\", \"v\".\"c1\", cast(\"v\".\"c1\" as bigint) from (VALUES (VAL)) do nothing returning \"result_file_key\".\"id\", \"result_file_key\".\"storage_key\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-6917261686713101878|-7926682800034401646|2823414612092473720|-8471148885826340209|1693072250386794298|8955811411867123301|-6123493279387241571|8248998745607509426|6122456175582542053|-7395113408842020082|-7906116866523953577|975648857598787274|-1207526402953341722|9170239395989070277|8705604785703460059|1954433539265878046|3868241215889854265|-4262129073508875423|7546638388950563311|-8752191020857263584|-6279851361347931869|2192158217673483829\"}[$__interval],\n\"query_key\", 'select distinct \"custom_field_schema\".\"custom_field_id\", \"v\".\"c1\" from (VALUES (VAL))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"8056810138825480563\"}[$__interval],\n\"query_key\", 'SELECT $$1 FROM ONLY \"public\".\"test_result\" x WHERE \"id\" OPERATOR(pg_catalog.=) $$1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-5777577502101448922|2204015473021674469|-8751758744933578627|-8661387132612092623|8988689615185466723|-3087464551001164855|5125311582038813815|-4545274812977225309|7440201726455517642|-4159708980869235145|4010418378022983869\"}[$__interval],\n\"query_key\", 'insert into \"test_result_members\" (\"test_result_id\", \"member_id\") select \"v\".\"c1\", \"v\".\"c1\" from (VALUES (VAL)) do nothing', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-7927966101046970345\"}[$__interval],\n\"query_key\", 'select distinct \"test_case\".\"id\", \"test_case\".\"name\", \"test_case\".\"automated\", \"test_case\".\"external\", \"test_case\".\"created_date\", \"status\".\"name\", \"status\".\"color\", \"test_layer\".\"name\" from \"test_case\" left outer join \"test_layer\" on \"test_case\".\"test_layer_id\" = \"test_layer\".\"id\" left outer join \"status\" on \"test_case\".\"status_id\" = \"status\".\"id\" where (\"test_case\".\"project_id\" = $$1 and \"test_case\".\"deleted\" = $$1 and $$1) order by \"test_case\".\"name\" asc limit $$1 offset $$1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-5044589254041591216|-7394040466574105525|-1496502837808951333|-8834231624922143969|-461000897443905194|5996753858410555356|-4656008474298022377|-6473903670838422887|-2335191902315472925|2045503430530144726|6647066941188965815|3157156254878637212|7627271497542721058|4157777325070427870|-7500316358865019996|7230479509350645395|4632669735404511504|2636309632352612502|5637223151890443871|-6432178765616075527|-6233797303980528554|2058979417252205266\"}[$__interval],\n\"query_key\", 'select distinct on (\"v\".\"c1\", \"custom_field_value\".\"id\") \"v\".\"c1\", \"custom_field_value\".\"id\" from (VALUES (VAL)) where \"custom_field_schema\".\"project_id\" = $$1 order by \"v\".\"c1\", \"custom_field_value\".\"id\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-1341247446993656083\"}[$__interval],\n\"query_key\", 'delete from \"attachment_candidate\" where $$1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-7992118653652790065\"}[$__interval],\n\"query_key\", 'SELECT $$1 FROM ONLY \"public\".\"custom_field_value\" x WHERE \"id\" OPERATOR(pg_catalog.=) $$1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-6240867104637883009\"}[$__interval],\n\"query_key\", 'SELECT $$1 FROM ONLY \"public\".\"launch\" x WHERE \"id\" OPERATOR(pg_catalog.=) $$1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-1626522373783870341|5401299768927847439|793108915342499657|974062286170248799|-3473505270933100475|2807897639485647490|8147682130394013929|2176605089775113363|6131085568087652298|-2963247187087305264\"}[$__interval],\n\"query_key\", 'with \"tr_cat\" as (select distinct on (\"test_result\".\"id\") \"test_result\".\"id\", \"category_matcher\".\"category_id\" from \"test_result\", \"category_matcher\" join \"project_category_matcher\" on \"project_category_matcher\".\"category_matcher_id\" = \"category_matcher\".\"id\" where (\"test_result\".\"launch_id\" = $$1 and \"test_result\".\"status\" is not null and \"test_result\".\"id\" IN KEYS and \"project_category_matcher\".\"project_id\" = $$1 and case when \"category_matcher\".\"message_regex\" is not null then (\"test_result\".\"message\" is not null and (\"test_result\".\"message\" ~* \"category_matcher\".\"message_regex\")) else $$1 end and case when \"category_matcher\".\"trace_regex\" is not null then (\"test_result\".\"trace\" is not null and (\"test_result\".\"trace\" ~* \"category_matcher\".\"trace_regex\")) else $$1 end and coalesce(\"check_regex\"(\"value\" := \"category_matcher\".\"message_regex\"), $$1) = $$1 and coalesce(\"check_regex\"(\"value\" := \"category_matcher\".\"trace_regex\"), $$1) = $$1) order by \"test_result\".\"id\", \"category_matcher\".\"id\") update \"test_result\" set \"category_id\" = \"tr_cat\".\"category_id\", \"last_modified_date\" = $$1, \"last_modified_by\" = $$1 from \"tr_cat\" where \"test_result\".\"id\" = \"tr_cat\".\"id\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3062618530441654868|-273069749762143538|5462372824747647259|-3246468056550652514|6117953940785709909|-7084735771075043339\"}[$__interval],\n\"query_key\", 'insert into \"attachment_candidate\" (\"test_session_id\", \"original_file_name\") select $$1, \"v\".\"c1\" from (VALUES (VAL)) order by \"v\".\"c1\" on conflict do nothing', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-6970450592140319731\"}[$__interval],\n\"query_key\", 'select \"launch\".\"id\", \"launch\".\"name\", \"launch\".\"project_id\", \"launch\".\"created_date\", \"launch\".\"last_modified_date\", \"launch\".\"created_by\", \"launch\".\"last_modified_by\", \"launch\".\"opt_lock\", \"launch\".\"closed\", \"launch\".\"external\", \"launch\".\"autoclose\" from \"launch\" where (\"launch\".\"project_id\" = $$1 and \"launch\".\"name\" ilike (($$1 || replace(replace(replace($$1, $$1, $$1), $$1, $$1), $$1, $$1)) || $$1) escape $$1 and exists (select $$1 as \"one\" from \"launch_launch_tag\" where (\"launch_launch_tag\".\"launch_id\" = \"launch\".\"id\" and \"launch_launch_tag\".\"launch_tag_id\" IN KEYS)) and exists (select $$1 as \"one\" from \"launch_launch_tag\" where (\"launch_launch_tag\".\"launch_id\" = \"launch\".\"id\" and \"launch_launch_tag\".\"launch_tag_id\" IN KEYS))) order by \"launch\".\"created_date\" desc limit $$1 offset $$1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"7641207739358637259\"}[$__interval],\n\"query_key\", 'select count(*) from \"launch\" where (\"launch\".\"project_id\" = $$1 and \"launch\".\"name\" ilike (($$1 || replace(replace(replace($$1, $$1, $$1), $$1, $$1), $$1, $$1)) || $$1) escape $$1 and exists (select $$1 as \"one\" from \"launch_launch_tag\" where (\"launch_launch_tag\".\"launch_id\" = \"launch\".\"id\" and \"launch_launch_tag\".\"launch_tag_id\" IN KEYS)) and exists (select $$1 as \"one\" from \"launch_launch_tag\" where (\"launch_launch_tag\".\"launch_id\" = \"launch\".\"id\" and \"launch_launch_tag\".\"launch_tag_id\" IN KEYS)))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"2791943185825238424|6676697615484508130|-5718804454333430684|1588938831491280182|9009870213525054378|-149484872841378996\"}[$__interval],\n\"query_key\", 'update \"attachment_candidate\" set \"storage_key\" = coalesce(\"v\".\"c1\", \"attachment_candidate\".\"storage_key\"), \"content_type\" = coalesce(\"v\".\"c1\", \"attachment_candidate\".\"content_type\"), \"content_length\" = coalesce(cast(\"v\".\"c1\" as bigint), \"attachment_candidate\".\"content_length\"), \"tra_id\" = coalesce(cast(\"v\".\"c1\" as bigint), \"attachment_candidate\".\"tra_id\"), \"tfra_id\" = coalesce(cast(\"v\".\"c1\" as bigint), \"attachment_candidate\".\"tfra_id\") from (VALUES (VAL)) returning \"attachment_candidate\".\"id\", \"attachment_candidate\".\"storage_key\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-4687070860694606995\"}[$__interval],\n\"query_key\", 'UPDATE shedlock SET lock_until = timezone($$1, CURRENT_TIMESTAMP) + cast($$1 as interval), locked_at = timezone($$1, CURRENT_TIMESTAMP), locked_by = $$1 WHERE shedlock.name = $$1 AND shedlock.lock_until <= timezone($$1, CURRENT_TIMESTAMP)', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-4114603877279967573\"}[$__interval],\n\"query_key\", 'select distinct on (\"test_result\".\"test_case_id\") \"test_result\".\"id\", \"test_result\".\"test_case_id\", \"test_case\".\"project_id\" from \"test_result\" join \"test_case\" on \"test_result\".\"test_case_id\" = \"test_case\".\"id\" join \"launch\" on \"test_result\".\"launch_id\" = \"launch\".\"id\" left outer join \"test_result\" as \"luf\" on \"test_case\".\"last_update_from\" = \"luf\".\"id\" left outer join \"launch\" as \"lufl\" on \"luf\".\"launch_id\" = \"lufl\".\"id\" where (\"test_result\".\"launch_id\" = $$1 and \"test_result\".\"hidden\" = $$1 and \"test_result\".\"external\" = $$1 and \"test_result\".\"status\" is not null and \"test_result\".\"test_case_id\" is not null and \"test_case\".\"project_id\" = $$1 and (\"lufl\".\"id\" = \"launch\".\"id\" or \"lufl\".\"id\" is null or \"lufl\".\"created_date\" < \"launch\".\"created_date\")) order by \"test_result\".\"test_case_id\", greatest(\"test_result\".\"start\", \"test_result\".\"stop\") desc nulls last, \"test_result\".\"created_date\" desc', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-2328707075574013363\"}[$__interval],\n\"query_key\", 'select \"tr_r\".\"id\", \"tr_r\".\"name\", \"tr_r\".\"test_case_id\", \"tr_r\".\"status\", count(*) as \"tr_r_cnt\", jsonb_agg(jsonb_build_object($$1, \"test_result\".\"id\", $$1, \"test_result\".\"name\", $$1, \"test_result\".\"status\") order by coalesce(\"test_result\".\"start\", \"test_result\".\"stop\", \"test_result\".\"created_date\") desc nulls last) from \"test_result\" join \"test_result\" as \"tr_r\" on \"test_result\".\"retried_by\" = \"tr_r\".\"id\" where (\"test_result\".\"launch_id\" = $$1 and \"tr_r\".\"hidden\" = $$1) group by \"tr_r\".\"id\" order by \"tr_r\".\"status\" asc limit $$1 offset $$1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"5430856273877324907|275869183699088795|6941294116127357973|-3878173460083974343|-8007480513439972348|8942890851767077132|1164336622995831865|3576885507386857744|781605339954230456|6954615694745995261|480732279668519574|4693973867568987586|-3406595629093823602|992361394160365876|1857141301873486552|2363038258762163628|1501374838212795469|-192621660505567593|-792828256830405386|-3093282474040622359|1058546147164372148|4710673510143931823\"}[$__interval],\n\"query_key\", 'select distinct \"role_schema\".\"role_id\", \"v\".\"c1\" from (VALUES (VAL))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"1415382740806871952\"}[$__interval],\n\"query_key\", 'SELECT $$1 FROM ONLY \"public\".\"test_session\" x WHERE \"id\" OPERATOR(pg_catalog.=) $$1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"1341378756493771417|-6246950554272617150|1092815620574559068|-6042788352534673534|-4799602003447500601|-7060170465313778346|2652581650408044487|-2672053638987449519|1211020225435069750|756949466228257143|4974529813685419266|-7891134231848604995|4136133300093520115|-7141447931217560349|-5079654247173618544|570173933609780278|4020876466584604372|-213428627839275220|-7010043108963930350|-4984997272525706056|8273409831913128349|-5305572006842993363\"}[$__interval],\n\"query_key\", 'select distinct on (\"v\".\"c1\", \"member\".\"id\") \"v\".\"c1\", \"member\".\"id\" from (VALUES (VAL)) where \"role_schema\".\"project_id\" = $$1 order by \"v\".\"c1\", \"member\".\"id\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"5547513614467208980\"}[$__interval],\n\"query_key\", 'insert into test_case_audit_log(test_case_id, data, dml_type) select o.id, jsonb_agg(build_jsonb_audit_diff(tg_table_name, keys, to_jsonb(o.*), to_jsonb(n.*))), $$1 from new_table n left join old_table o using (id) where jsonb_diff_val(to_jsonb(o.*), to_jsonb(n.*), keys) <> $$1::jsonb group by o.id', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3069081473235762728\"}[$__interval],\n\"query_key\", 'SELECT $$1 FROM ONLY \"public\".\"test_case\" x WHERE \"id\" OPERATOR(pg_catalog.=) $$1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-4978302740586495005\"}[$__interval],\n\"query_key\", 'select \"launch\".\"id\" from \"launch\" where (\"launch\".\"project_id\" = $$1 and \"launch\".\"closed\" = $$1 and \"launch\".\"last_modified_date\" <= $$1 and ((not exists (select $$1 as \"one\" from \"test_result\" where (\"test_result\".\"launch_id\" = \"launch\".\"id\" and \"test_result\".\"status\" is null)) and not exists (select $$1 as \"one\" from \"job_run\" where (\"job_run\".\"launch_id\" = \"launch\".\"id\" and \"job_run\".\"stage\" not IN KEYS, cast($$1 as \"job_run_stage\")))) and not exists (select $$1 as \"one\" from \"result_file_key\" join \"test_session\" on \"result_file_key\".\"test_session_id\" = \"test_session\".\"id\" where \"test_session\".\"launch_id\" = \"launch\".\"id\") and (\"launch\".\"autoclose\" = $$1 or $$1 or \"launch\".\"last_modified_date\" <= $$1)) or (not (not exists (select $$1 as \"one\" from \"test_result\" where (\"test_result\".\"launch_id\" = \"launch\".\"id\" and \"test_result\".\"status\" is null)) and not exists (select $$1 as \"one\" from \"job_run\" where (\"job_run\".\"launch_id\" = \"launch\".\"id\" and \"job_run\".\"stage\" not IN KEYS, cast($$1 as \"job_run_stage\")))) and not exists (select $$1 as \"one\" from \"result_file_key\" join \"test_session\" on \"result_file_key\".\"test_session_id\" = \"test_session\".\"id\" where \"test_session\".\"launch_id\" = \"launch\".\"id\")) and \"launch\".\"last_modified_date\" <= $$1)))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3235926796831138437\"}[$__interval],\n\"query_key\", 'select count(*) from \"launch\" where (\"launch\".\"project_id\" = $$1 and exists (select $$1 as \"one\" from \"launch_launch_tag\" where (\"launch_launch_tag\".\"launch_id\" = \"launch\".\"id\" and \"launch_launch_tag\".\"launch_tag_id\" IN KEYS)) and \"launch\".\"name\" ilike (($$1 || replace(replace(replace($$1, $$1, $$1), $$1, $$1), $$1, $$1)) || $$1) escape $$1)', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"7186857496303958713\"}[$__interval],\n\"query_key\", 'select \"test_session\".\"id\", \"launch\".\"id\", \"launch\".\"project_id\" from \"test_session\" join \"launch\" on \"test_session\".\"launch_id\" = \"launch\".\"id\" where \"test_session\".\"id\" = $$1 limit $$1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-2815449590150330190\"}[$__interval],\n\"query_key\", 'select exists (select $$1 as \"one\" from \"launch\" where (\"launch\".\"id\" = $$1 and \"launch\".\"closed\" = $$1))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"4367618082213034417|8223656614941045312|-228307855204130051|-4003431100748047151|-8336129075704408581\"}[$__interval],\n\"query_key\", 'update \"test_result\" set \"muted\" = $$1, \"last_modified_by\" = $$1, \"last_modified_date\" = $$1 from \"mute\" where \"test_result\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"5400071958608406872\"}[$__interval],\n\"query_key\", 'select row (\"mute\".\"id\", \"mute\".\"test_case_id\", \"mute\".\"reason\", \"mute\".\"reason_html\", \"mute\".\"created_date\", \"mute\".\"last_modified_date\", \"mute\".\"created_by\", \"mute\".\"last_modified_by\", \"mute\".\"opt_lock\", \"mute\".\"name\") as \"mute\", (select coalesce(jsonb_agg(jsonb_build_array(\"v1\", \"v1\", \"v1\", \"v1\", \"v1\", \"v1\", \"v1\")), jsonb_build_array()) from (select \"issue\".\"id\" as \"v1\", \"issue\".\"name\" as \"v1\", \"issue\".\"integration_id\" as \"v1\", \"issue\".\"summary\" as \"v1\", \"issue\".\"url\" as \"v1\", \"issue\".\"status\" as \"v1\", \"issue\".\"closed\" as \"v1\" from \"issue\" where exists (select $$1 as \"one\" from \"mute_issue\" where (\"mute_issue\".\"issue_id\" = \"issue\".\"id\" and \"mute_issue\".\"mute_id\" = \"mute\".\"id\")) order by \"issue\".\"name\" limit $$1) as \"t\") from \"mute\" where \"mute\".\"test_case_id\" = $$1 order by \"mute\".\"created_date\" asc limit $$1 offset $$1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3998338501921065332\"}[$__interval],\n\"query_key\", 'insert into test_case_audit_log(test_case_id, data, dml_type) select o.test_case_id, build_jsonb_audit_rel_diff( tg_table_name, jsonb_agg(to_jsonb(o.*) -> columnName), $$1::jsonb ), $$1 from old_table o inner join test_case tc on tc.id = o.test_case_id group by o.test_case_id', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-5039779443449745149\"}[$__interval],\n\"query_key\", 'select count(*) from \"launch\" where (\"launch\".\"project_id\" = $$1 and \"launch\".\"name\" ilike (($$1 || replace(replace(replace($$1, $$1, $$1), $$1, $$1), $$1, $$1)) || $$1) escape $$1 and exists (select $$1 as \"one\" from \"launch_launch_tag\" where (\"launch_launch_tag\".\"launch_id\" = \"launch\".\"id\" and \"launch_launch_tag\".\"launch_tag_id\" IN KEYS)) and \"launch\".\"created_date\" >= $$1 and \"launch\".\"created_date\" <= $$1)', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"6796703815875150037\"}[$__interval],\n\"query_key\", 'delete from \"test_case_example\" where \"test_case_example\".\"test_case_id\" IN KEYS)', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"3001386143669856305\"}[$__interval],\n\"query_key\", 'insert into blob_remove_task(storage_key) select o.storage_key from old_table o where o.storage_key is not null on conflict do nothing', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-5549731158334371028|3499547494232853299|8924296856613228623|7197594327390788852|-5163038821546204447|-1018796979344459274|1450529191045924075|1218604733433657688|855444771396498542|-3896712869998310513|8691512920017643455|3218429512401457862|-7884745926230104318|6297388951006023184|4080997874459877913|7590648649901440012|3582885391849600098|731594648730650608|-5145311632729457178|-6657831383533187059|5410550208065994948|4179773768385444470|-8848823104547799472|-5412624878065082016\"}[$__interval],\n\"query_key\", 'select distinct \"env_var_schema\".\"env_var_id\", \"v\".\"c1\" from (VALUES (VAL))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-6562429561190582604|-8803273187448260302|3059711883474855560|-6167458461108275078|958018144603841483|8987624692599113825|5615623784443322959|-3372235522892940691|-6628820825263961640|1627167073502469990|-8540964994056176648|-7658139608759289041|-8444285810905297930|-4965917749170345205|-4895004090125626544|-5052826391655082162|5159298838152610356|1018972790748866543|-391974972876488967|-547465386380128264|-3440204244019180485|2308552146883460710|8982225239208012124|142565839398527295\"}[$__interval],\n\"query_key\", 'select distinct on (\"v\".\"c1\", \"env_var_value\".\"id\") \"v\".\"c1\", \"env_var_value\".\"id\" from (VALUES (VAL)) where \"env_var_schema\".\"project_id\" = $$1 order by \"v\".\"c1\", \"env_var_value\".\"id\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-482806124576001773|-2729862619083974672|-9074900260879747961|-681799089771740380|1059258721662756204|-1386124859591062843|-5469076252033112801|-7364113469591221777|-3998707822841244244|996449913849870153|-1875409092867663629|5536789896713291599|7368534306746241615|8976905801016573317|1429572330451522465|-949859561033659837|3311349477226399565|6476481770425911328|8996918343209267281|6200802428157051363|4125083630921296239|5201007064017760142|4107535605951763053|6717907907251356823\"}[$__interval],\n\"query_key\", 'select distinct \"issue_schema\".\"integration_id\", \"v\".\"c1\" from (VALUES (VAL))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"2368764783907856578\"}[$__interval],\n\"query_key\", 'SELECT $$1 FROM ONLY \"public\".\"job_run\" x WHERE \"id\" OPERATOR(pg_catalog.=) $$1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"3613318984141109093\"}[$__interval],\n\"query_key\", 'select \"launch\".\"id\", \"launch\".\"project_id\", \"launch\".\"closed\" from \"test_session\" join \"launch\" on \"test_session\".\"launch_id\" = \"launch\".\"id\" where \"test_session\".\"id\" = $$1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-6240867104637883009\"}[$__interval],\n\"query_key\", 'SELECT $1 FROM ONLY \"public\".\"launch\" x WHERE \"id\" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-5961531816685115219|5348561853148171200|-2024315525205880296|-3946352109319617114|-7114134203024639928|3857573856810294698|4696212443935485341|3243486293748510443\"}[$__interval],\n\"query_key\", 'update \"test_result\" set \"scenario_key\" = $1, \"last_modified_by\" = $1, \"last_modified_date\" = $1 where \"test_result\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3069081473235762728\"}[$__interval],\n\"query_key\", 'SELECT $1 FROM ONLY \"public\".\"test_case\" x WHERE \"id\" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"8056810138825480563\"}[$__interval],\n\"query_key\", 'SELECT $1 FROM ONLY \"public\".\"test_result\" x WHERE \"id\" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"2368764783907856578\"}[$__interval],\n\"query_key\", 'SELECT $1 FROM ONLY \"public\".\"job_run\" x WHERE \"id\" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-2077094910282544909\"}[$__interval],\n\"query_key\", 'insert into blob_remove_task (storage_key) VALUES (VAL) on conflict do nothing', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-7992118653652790065\"}[$__interval],\n\"query_key\", 'SELECT $1 FROM ONLY \"public\".\"custom_field_value\" x WHERE \"id\" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-4687070860694606995\"}[$__interval],\n\"query_key\", 'UPDATE shedlock SET lock_until = timezone($1, CURRENT_TIMESTAMP) + cast($1 as interval), locked_at = timezone($1, CURRENT_TIMESTAMP), locked_by = $1 WHERE shedlock.name = $1 AND shedlock.lock_until <= timezone($1, CURRENT_TIMESTAMP)', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"1415382740806871952\"}[$__interval],\n\"query_key\", 'SELECT $1 FROM ONLY \"public\".\"test_session\" x WHERE \"id\" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"1157584214810043055\"}[$__interval],\n\"query_key\", 'update \"launch\" set \"last_modified_date\" = $1, \"last_modified_by\" = $1 where \"launch\".\"id\" = $1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3934084821068338370|-7629315488505523782|-9118850505870576616|-1407348636818196047|5343797223471241302|-1724946079165604596|-3314170056428998073|-5599554464466329331\"}[$__interval],\n\"query_key\", 'with \"tr_lk\" as (select \"test_result\".\"id\" from \"test_result\" where (\"test_result\".\"launch_id\" = $1 and \"test_result\".\"history_key\" IN KEYS) order by \"test_result\".\"id\" for no key update), \"tr_rt\" as (select \"test_result\".\"id\", first_value(\"test_result\".\"id\") over (partition by \"test_result\".\"history_key\" order by coalesce(\"test_result\".\"start\", \"test_result\".\"stop\", \"test_result\".\"created_date\") desc nulls last) as \"tr1\" from \"tr_lk\" join \"test_result\" on \"test_result\".\"id\" = \"tr_lk\".\"id\" order by \"test_result\".\"id\") update \"test_result\" set \"hidden\" = (\"test_result\".\"id\" <> \"tr_rt\".\"tr1\"), \"retried_by\" = case when \"test_result\".\"id\" <> \"tr_rt\".\"tr1\" then \"tr_rt\".\"tr1\" else cast($1 as bigint) end, \"last_modified_by\" = $1, \"last_modified_date\" = $1 from \"tr_rt\" where \"test_result\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-1890520225001541202|8541189628386284755|-6729167206932895045|-4956885308137481126|-7851074193500501429|8309675949422813515|-2562509008144719696|5387232704629596238|-5557594060599571491\"}[$__interval],\n\"query_key\", 'update \"test_result\" set \"full_name\" = \"v\".\"c1\", \"description\" = \"v\".\"c1\", \"description_html\" = \"v\".\"c1\", \"precondition\" = \"v\".\"c1\", \"precondition_html\" = \"v\".\"c1\", \"expected_result\" = \"v\".\"c1\", \"expected_result_html\" = \"v\".\"c1\", \"test_layer_id\" = cast(\"v\".\"c1\" as bigint), \"manual\" = \"v\".\"c1\", \"status\" = \"v\".\"c1\", \"message\" = \"v\".\"c1\", \"trace\" = \"v\".\"c1\", \"start\" = cast(\"v\".\"c1\" as bigint), \"stop\" = cast(\"v\".\"c1\" as bigint), \"duration\" = cast(\"v\".\"c1\" as bigint), \"host_id\" = \"v\".\"c1\", \"thread_id\" = \"v\".\"c1\", \"local_run_uuid\" = \"v\".\"c1\" from (VALUES (VAL)) where \"test_result\".\"id\" = \"v\".\"c1\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"354776470543819834|-2013418728145581168|-5941973755437388416|-1138148854663917314|-6151010435157117400|1504231528310994426|6771795209721327702|8264927604351288767|1031709803157834306\"}[$__interval],\n\"query_key\", 'insert into \"test_result\" (\"launch_id\", \"test_session_id\", \"job_run_id\", \"id\", \"test_case_id\", \"name\", \"history_key\", \"hidden\", \"external\", \"created_by\", \"created_date\", \"last_modified_by\", \"last_modified_date\") VALUES (VAL) do update set \"launch_id\" = \"excluded\".\"launch_id\", \"test_session_id\" = \"excluded\".\"test_session_id\", \"job_run_id\" = \"excluded\".\"job_run_id\", \"test_case_id\" = \"excluded\".\"test_case_id\", \"name\" = \"excluded\".\"name\", \"history_key\" = \"excluded\".\"history_key\", \"hidden\" = $1, \"external\" = $1, \"last_modified_by\" = $1, \"last_modified_date\" = $1 returning \"test_result\".\"id\", \"test_result\".\"test_case_id\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"5440757910167813368|-2754656615418654773|4447347532761596015|-4985950084870127777|4066338591555528632|2783677633027607696|3306178492070608084|3224420977893184079\"}[$__interval],\n\"query_key\", 'insert into \"test_result_scenario_block\" (\"test_result_id\", \"data\", \"created_by\", \"created_date\", \"last_modified_by\", \"last_modified_date\") select \"v\".\"c1\", \"v\".\"c1\", $1, $1, $1, $1 from (VALUES (VAL)) do update set \"data\" = \"excluded\".\"data\", \"last_modified_by\" = $1, \"last_modified_date\" = $1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-8946200807776987162|-9200057509331791363|-8063467946522176185|435219297541885788|-3665261003842485834|8252378364890499554|-5024892381980960465\"}[$__interval],\n\"query_key\", 'select bool_and(exists (with \"up_cte\" as (((select distinct \"permission_permission_set\".\"permission\" from \"group_project_access\" join \"access_group\" on \"group_project_access\".\"group_id\" = \"access_group\".\"id\" join \"group_user\" on \"group_user\".\"group_id\" = \"access_group\".\"id\" join \"permission_permission_set\" on \"permission_permission_set\".\"permission_set_id\" = \"group_project_access\".\"permission_set_id\" where (\"group_project_access\".\"project_id\" = \"project\".\"id\" and \"group_user\".\"username\" = $1 and (\"access_group\".\"personal\" = $1 or (\"access_group\".\"personal\" = $1 and \"access_group\".\"name\" = $1)))) union all (select \"v\".\"c1\" from (VALUES (VAL)) from \"project\" where \"project\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"6973423874184579389|1931361531336001837|6134564063525871934|892735712321394778|-6454084909132048456|-6267104841689983545|800169189322848841|1835519071896069564|-5670520736262774960|7289690819468492297|-719898416793592636|-3171469207843903637|6656928851985625580|-4532199773036126758|5246163688087098552|7856500316668066297\"}[$__interval],\n\"query_key\", 'insert into \"test_result_custom_field\" (\"test_result_id\", \"custom_field_value_id\") select \"v\".\"c1\", \"v\".\"c1\" from (VALUES (VAL)) do nothing', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-1416140981673074347\"}[$__interval],\n\"query_key\", 'select distinct \"test_result\".\"id\", \"test_result\".\"name\", \"test_result\".\"status\", \"test_result\".\"start\", \"test_result\".\"stop\", \"test_result\".\"duration\", \"test_result\".\"manual\", \"test_result\".\"assignee\", \"test_result\".\"tested_by\", \"test_result\".\"test_case_id\", \"test_layer\".\"name\", -(\"test_result\".\"status\") from \"test_result\" left outer join \"test_layer\" on \"test_result\".\"test_layer_id\" = \"test_layer\".\"id\" where (\"test_result\".\"launch_id\" = $1 and \"test_result\".\"hidden\" = $1 and $1) order by \"test_result\".\"test_case_id\" asc limit $1 offset $1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-81176439872564081|17670673547066367|1545784804722760381|-4488997511127977649|3958803941604940321|-3950490104272315063|-9174957291846684074|2956845977626877848|2624756295929383646|-4864816528718272866\"}[$__interval],\n\"query_key\", 'delete from \"result_file_key\" where \"result_file_key\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-4978302740586495005\"}[$__interval],\n\"query_key\", 'select \"launch\".\"id\" from \"launch\" where (\"launch\".\"project_id\" = $1 and \"launch\".\"closed\" = $1 and \"launch\".\"last_modified_date\" <= $1 and ((not exists (select $1 as \"one\" from \"test_result\" where (\"test_result\".\"launch_id\" = \"launch\".\"id\" and \"test_result\".\"status\" is null)) and not exists (select $1 as \"one\" from \"job_run\" where (\"job_run\".\"launch_id\" = \"launch\".\"id\" and \"job_run\".\"stage\" not IN KEYS, cast($1 as \"job_run_stage\")))) and not exists (select $1 as \"one\" from \"result_file_key\" join \"test_session\" on \"result_file_key\".\"test_session_id\" = \"test_session\".\"id\" where \"test_session\".\"launch_id\" = \"launch\".\"id\") and (\"launch\".\"autoclose\" = $1 or $1 or \"launch\".\"last_modified_date\" <= $1)) or (not (not exists (select $1 as \"one\" from \"test_result\" where (\"test_result\".\"launch_id\" = \"launch\".\"id\" and \"test_result\".\"status\" is null)) and not exists (select $1 as \"one\" from \"job_run\" where (\"job_run\".\"launch_id\" = \"launch\".\"id\" and \"job_run\".\"stage\" not IN KEYS, cast($1 as \"job_run_stage\")))) and not exists (select $1 as \"one\" from \"result_file_key\" join \"test_session\" on \"result_file_key\".\"test_session_id\" = \"test_session\".\"id\" where \"test_session\".\"launch_id\" = \"launch\".\"id\")) and \"launch\".\"last_modified_date\" <= $1)))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-1341247446993656083\"}[$__interval],\n\"query_key\", 'delete from \"attachment_candidate\" where $1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3065101627323191925|6172012046876450672|-154770314165353031|-4713854124755418034|-5345628697385564956|-4444445086239616450|8288715177846116362|-5728658692971845333|4285799337526335392\"}[$__interval],\n\"query_key\", 'with \"exp_tr1\" as (select distinct on (\"v\".\"c1\") \"v\".\"c1\", \"test_result\".\"id\" from \"test_result\" join (VALUES (VAL)) select \"exp_tr1\".\"c1\", \"test_result\".\"id\" from \"test_result\" join \"exp_tr1\" on \"test_result\".\"id\" = \"exp_tr1\".\"id\" order by \"test_result\".\"id\" for no key update skip locked', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-4459481342769312776\"}[$__interval],\n\"query_key\", 'select count(*) from \"test_result\" where (\"test_result\".\"launch_id\" = $1 and \"test_result\".\"hidden\" = $1 and $1)', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-5352755801224380671|-7232752617337134793|2126783132189623321|-6011106520953329790|8360599381691416625|-5387688731442853877|4373750156909557718|7294443988928756034|3027496910096275572|-7626796848630585055\"}[$__interval],\n\"query_key\", 'insert into \"result_file_key\" (\"test_session_id\", \"original_file_name\", \"storage_key\", \"content_type\", \"content_length\") select $1, \"v\".\"c1\", \"v\".\"c1\", \"v\".\"c1\", cast(\"v\".\"c1\" as bigint) from (VALUES (VAL)) do nothing returning \"result_file_key\".\"id\", \"result_file_key\".\"storage_key\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"8985625205764313059\"}[$__interval],\n\"query_key\", 'select \"test_result\".\"status\", count(\"test_result\") from \"test_result\" where (\"test_result\".\"launch_id\" = $1 and \"test_result\".\"muted\" = $1 and \"test_result\".\"hidden\" = $1) group by \"test_result\".\"status\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"3001386143669856305\"}[$__interval],\n\"query_key\", 'insert into blob_remove_task(storage_key) select o.storage_key from old_table o where o.storage_key is not null on conflict do nothing', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"7186857496303958713\"}[$__interval],\n\"query_key\", 'select \"test_session\".\"id\", \"launch\".\"id\", \"launch\".\"project_id\" from \"test_session\" join \"launch\" on \"test_session\".\"launch_id\" = \"launch\".\"id\" where \"test_session\".\"id\" = $1 limit $1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-2815449590150330190\"}[$__interval],\n\"query_key\", 'select exists (select $1 as \"one\" from \"launch\" where (\"launch\".\"id\" = $1 and \"launch\".\"closed\" = $1))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-5777577502101448922|2204015473021674469|-8751758744933578627|-8661387132612092623|8988689615185466723|-3087464551001164855|5125311582038813815|-4545274812977225309|7440201726455517642|-4159708980869235145|4010418378022983869\"}[$__interval],\n\"query_key\", 'insert into \"test_result_members\" (\"test_result_id\", \"member_id\") select \"v\".\"c1\", \"v\".\"c1\" from (VALUES (VAL)) do nothing', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-6917261686713101878|-7926682800034401646|2823414612092473720|-8471148885826340209|1693072250386794298|8955811411867123301|-6123493279387241571|8248998745607509426|6122456175582542053|-7395113408842020082|-7906116866523953577|975648857598787274|-1207526402953341722|9170239395989070277|8705604785703460059|1954433539265878046|3868241215889854265|-4262129073508875423|7546638388950563311|-8752191020857263584|-6279851361347931869|2192158217673483829\"}[$__interval],\n\"query_key\", 'select distinct \"custom_field_schema\".\"custom_field_id\", \"v\".\"c1\" from (VALUES (VAL))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"3415057726328186314|118716905370055968|6054185593216042258|-4682194556151941318|-2764246633192238751|-1294727602406559514|-6336725022792132409|-7287447943429565885|1103572228662402772|3327111597703155155|8341980863677065211\"}[$__interval],\n\"query_key\", 'insert into \"test_result_environment\" (\"test_result_id\", \"env_var_value_id\") select \"v\".\"c1\", \"v\".\"c1\" from (VALUES (VAL)) do nothing', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"3613318984141109093\"}[$__interval],\n\"query_key\", 'select \"launch\".\"id\", \"launch\".\"project_id\", \"launch\".\"closed\" from \"test_session\" join \"launch\" on \"test_session\".\"launch_id\" = \"launch\".\"id\" where \"test_session\".\"id\" = $1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-5044589254041591216|-7394040466574105525|-1496502837808951333|-8834231624922143969|-461000897443905194|5996753858410555356|-4656008474298022377|-6473903670838422887|-2335191902315472925|2045503430530144726|6647066941188965815|3157156254878637212|7627271497542721058|4157777325070427870|-7500316358865019996|7230479509350645395|4632669735404511504|2636309632352612502|5637223151890443871|-6432178765616075527|-6233797303980528554|2058979417252205266\"}[$__interval],\n\"query_key\", 'select distinct on (\"v\".\"c1\", \"custom_field_value\".\"id\") \"v\".\"c1\", \"custom_field_value\".\"id\" from (VALUES (VAL)) where \"custom_field_schema\".\"project_id\" = $1 order by \"v\".\"c1\", \"custom_field_value\".\"id\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3514639611992162825\"}[$__interval],\n\"query_key\", 'set \"allure.current_username\" = \\'_system\\'', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-1626522373783870341|5401299768927847439|793108915342499657|974062286170248799|-3473505270933100475|2807897639485647490|8147682130394013929|2176605089775113363|6131085568087652298|-2963247187087305264\"}[$__interval],\n\"query_key\", 'with \"tr_cat\" as (select distinct on (\"test_result\".\"id\") \"test_result\".\"id\", \"category_matcher\".\"category_id\" from \"test_result\", \"category_matcher\" join \"project_category_matcher\" on \"project_category_matcher\".\"category_matcher_id\" = \"category_matcher\".\"id\" where (\"test_result\".\"launch_id\" = $1 and \"test_result\".\"status\" is not null and \"test_result\".\"id\" IN KEYS and \"project_category_matcher\".\"project_id\" = $1 and case when \"category_matcher\".\"message_regex\" is not null then (\"test_result\".\"message\" is not null and (\"test_result\".\"message\" ~* \"category_matcher\".\"message_regex\")) else $1 end and case when \"category_matcher\".\"trace_regex\" is not null then (\"test_result\".\"trace\" is not null and (\"test_result\".\"trace\" ~* \"category_matcher\".\"trace_regex\")) else $1 end and coalesce(\"check_regex\"(\"value\" := \"category_matcher\".\"message_regex\"), $1) = $1 and coalesce(\"check_regex\"(\"value\" := \"category_matcher\".\"trace_regex\"), $1) = $1) order by \"test_result\".\"id\", \"category_matcher\".\"id\") update \"test_result\" set \"category_id\" = \"tr_cat\".\"category_id\", \"last_modified_date\" = $1, \"last_modified_by\" = $1 from \"tr_cat\" where \"test_result\".\"id\" = \"tr_cat\".\"id\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-8563724570961568754\"}[$__interval],\n\"query_key\", 'select (((($1 || cast(\"env_var_value\".\"env_var_id\" as varchar)) || $1) || \"env_var_value\".\"name\") || $1) from \"env_var_value\" where \"env_var_value\".\"id\" IN KEYS order by \"env_var_value\".\"id\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-2246384007061310229\"}[$__interval],\n\"query_key\", 'select \"attachment_candidate\".\"id\" from \"attachment_candidate\" where (\"attachment_candidate\".\"test_session_id\" = $1 and \"attachment_candidate\".\"storage_key\" is not null and $1 and (\"attachment_candidate\".\"tra_id\" is not null or \"attachment_candidate\".\"tfra_id\" is not null)) order by \"attachment_candidate\".\"test_session_id\", \"attachment_candidate\".\"original_file_name\" for update skip locked', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-8559739897604239156\"}[$__interval],\n\"query_key\", 'select \"test_session_environment\".\"env_var_value_id\" from \"test_session_environment\" where \"test_session_environment\".\"test_session_id\" = $1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"5400071958608406872\"}[$__interval],\n\"query_key\", 'select row (\"mute\".\"id\", \"mute\".\"test_case_id\", \"mute\".\"reason\", \"mute\".\"reason_html\", \"mute\".\"created_date\", \"mute\".\"last_modified_date\", \"mute\".\"created_by\", \"mute\".\"last_modified_by\", \"mute\".\"opt_lock\", \"mute\".\"name\") as \"mute\", (select coalesce(jsonb_agg(jsonb_build_array(\"v1\", \"v1\", \"v1\", \"v1\", \"v1\", \"v1\", \"v1\")), jsonb_build_array()) from (select \"issue\".\"id\" as \"v1\", \"issue\".\"name\" as \"v1\", \"issue\".\"integration_id\" as \"v1\", \"issue\".\"summary\" as \"v1\", \"issue\".\"url\" as \"v1\", \"issue\".\"status\" as \"v1\", \"issue\".\"closed\" as \"v1\" from \"issue\" where exists (select $1 as \"one\" from \"mute_issue\" where (\"mute_issue\".\"issue_id\" = \"issue\".\"id\" and \"mute_issue\".\"mute_id\" = \"mute\".\"id\")) order by \"issue\".\"name\" limit $1) as \"t\") from \"mute\" where \"mute\".\"test_case_id\" = $1 order by \"mute\".\"created_date\" asc limit $1 offset $1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"6539232846217616083\"}[$__interval],\n\"query_key\", 'SELECT $1 FROM ONLY \"public\".\"env_var_value\" x WHERE \"id\" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"5430856273877324907|275869183699088795|6941294116127357973|-3878173460083974343|-8007480513439972348|8942890851767077132|1164336622995831865|3576885507386857744|781605339954230456|6954615694745995261|480732279668519574|4693973867568987586|-3406595629093823602|992361394160365876|1857141301873486552|2363038258762163628|1501374838212795469|-192621660505567593|-792828256830405386|-3093282474040622359|1058546147164372148|4710673510143931823\"}[$__interval],\n\"query_key\", 'select distinct \"role_schema\".\"role_id\", \"v\".\"c1\" from (VALUES (VAL))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-2876710813037661000\"}[$__interval],\n\"query_key\", 'SELECT $1 FROM ONLY \"public\".\"member\" x WHERE \"id\" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"1341378756493771417|-6246950554272617150|1092815620574559068|-6042788352534673534|-4799602003447500601|-7060170465313778346|2652581650408044487|-2672053638987449519|1211020225435069750|756949466228257143|4974529813685419266|-7891134231848604995|4136133300093520115|-7141447931217560349|-5079654247173618544|570173933609780278|4020876466584604372|-213428627839275220|-7010043108963930350|-4984997272525706056|8273409831913128349|-5305572006842993363\"}[$__interval],\n\"query_key\", 'select distinct on (\"v\".\"c1\", \"member\".\"id\") \"v\".\"c1\", \"member\".\"id\" from (VALUES (VAL)) where \"role_schema\".\"project_id\" = $1 order by \"v\".\"c1\", \"member\".\"id\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3684714475872198064\"}[$__interval],\n\"query_key\", 'select \"test_session\".\"id\", \"test_session\".\"job_run_id\", \"test_session\".\"launch_id\", \"test_session\".\"created_date\", \"test_session\".\"last_modified_date\", \"test_session\".\"created_by\", \"test_session\".\"last_modified_by\", \"test_session\".\"opt_lock\" from \"test_session\" where \"test_session\".\"id\" = $1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-288291229991999799\"}[$__interval],\n\"query_key\", 'select \"test_case_update_schema\".\"field\" from \"test_case_update_schema\" where (\"test_case_update_schema\".\"project_id\" = $1 and \"test_case_update_schema\".\"policy\" = cast($1 as \"test_case_update_schema_policy\"))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-5549731158334371028|3499547494232853299|8924296856613228623|7197594327390788852|-5163038821546204447|-1018796979344459274|1450529191045924075|1218604733433657688|855444771396498542|-3896712869998310513|8691512920017643455|3218429512401457862|-7884745926230104318|6297388951006023184|4080997874459877913|7590648649901440012|3582885391849600098|731594648730650608|-5145311632729457178|-6657831383533187059|5410550208065994948|4179773768385444470|-8848823104547799472|-5412624878065082016\"}[$__interval],\n\"query_key\", 'select distinct \"env_var_schema\".\"env_var_id\", \"v\".\"c1\" from (VALUES (VAL))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"5566255062937410576|-3377572827424077950|-2501223741679151296|3405375341494536498|9033811209553257769|-1138723468542675049|-6027273077881459161|-69089279660994826|1139074439244915757|4429660887963056662\"}[$__interval],\n\"query_key\", 'select \"result_file_key\".\"id\" from \"result_file_key\" where \"result_file_key\".\"id\" IN KEYS order by \"result_file_key\".\"id\" for update', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"4367618082213034417|8223656614941045312|-228307855204130051|-4003431100748047151|-8336129075704408581\"}[$__interval],\n\"query_key\", 'update \"test_result\" set \"muted\" = $1, \"last_modified_by\" = $1, \"last_modified_date\" = $1 from \"mute\" where \"test_result\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-1367109535527251860|2490831401377767406|880265226657244165|603124000510431788|-6157976047926418273|7238539840658533655|4444676047969189582|-8354590333192781635|-2908414148123392591|2702217437151857215|6432109354647016355\"}[$__interval],\n\"query_key\", 'select \"result_file_key\".\"id\", \"result_file_key\".\"test_session_id\", \"result_file_key\".\"original_file_name\", \"result_file_key\".\"content_type\", \"result_file_key\".\"content_length\", \"result_file_key\".\"storage_key\" from \"result_file_key\" where \"result_file_key\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-6562429561190582604|-8803273187448260302|3059711883474855560|-6167458461108275078|958018144603841483|8987624692599113825|5615623784443322959|-3372235522892940691|-6628820825263961640|1627167073502469990|-8540964994056176648|-7658139608759289041|-8444285810905297930|-4965917749170345205|-4895004090125626544|-5052826391655082162|5159298838152610356|1018972790748866543|-391974972876488967|-547465386380128264|-3440204244019180485|2308552146883460710|8982225239208012124|142565839398527295\"}[$__interval],\n\"query_key\", 'select distinct on (\"v\".\"c1\", \"env_var_value\".\"id\") \"v\".\"c1\", \"env_var_value\".\"id\" from (VALUES (VAL)) where \"env_var_schema\".\"project_id\" = $1 order by \"v\".\"c1\", \"env_var_value\".\"id\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-482806124576001773|-2729862619083974672|-9074900260879747961|-681799089771740380|1059258721662756204|-1386124859591062843|-5469076252033112801|-7364113469591221777|-3998707822841244244|996449913849870153|-1875409092867663629|5536789896713291599|7368534306746241615|8976905801016573317|1429572330451522465|-949859561033659837|3311349477226399565|6476481770425911328|8996918343209267281|6200802428157051363|4125083630921296239|5201007064017760142|4107535605951763053|6717907907251356823\"}[$__interval],\n\"query_key\", 'select distinct \"issue_schema\".\"integration_id\", \"v\".\"c1\" from (VALUES (VAL))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"5479385907598248344|1046285071778547826|-5762773052760867579|-2686436015035622133|-3105583801646583162|2324183697523981298|-2412409241012876928|-8547761970420346568|5674482460232636142|3601418848676153229\"}[$__interval],\n\"query_key\", 'select distinct \"test_result\".\"history_key\" from \"test_result\" where \"test_result\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"5786950750983389405|5082956433059641538|4526697823493061129|1714768012446746209|1983382004170680133|584330918221949265|2081419779562521318|7957046330897662366|-6255430219020073723|6346345423624416038|-6371614741821262314|-8002920695416888761|4763622152919194278|5072746181820023541|-6315587663371436725|1403067826481958230|-68846153109438198|-6065878892723770070|7526199377097652122|3999453922122517646|4487422152379382009|8445403457854073233|-1216213262476386390|7401168037741311367\"}[$__interval],\n\"query_key\", 'select distinct on (\"v\".\"c1\", \"issue\".\"id\") \"v\".\"c1\", \"issue\".\"id\" from (VALUES (VAL)) where \"issue_schema\".\"project_id\" = $1 order by \"v\".\"c1\", \"issue\".\"id\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3391531037701451365|2553608325821469152\"}[$__interval],\n\"query_key\", 'insert into \"test_result_test_tag\" (\"test_result_id\", \"test_tag_id\") select \"v\".\"c1\", \"v\".\"c1\" from (VALUES (VAL)) do nothing', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3998338501921065332\"}[$__interval],\n\"query_key\", 'insert into test_case_audit_log(test_case_id, data, dml_type) select o.test_case_id, build_jsonb_audit_rel_diff( tg_table_name, jsonb_agg(to_jsonb(o.*) -> columnName), $1::jsonb ), $1 from old_table o inner join test_case tc on tc.id = o.test_case_id group by o.test_case_id', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"1403618141198530023|-4618009157953899239|-2137553582591360288|4267187731898672217|-2840636657725829248|4572117339552076275|7755903593909080209|887262880973629804|-3525691336881643393|2726663908950510626|7568161300913741959|-8892702834469376458|853413171175627699|-4684444474341164671|-4257393876722780439|2320807654027864014|-1753576815896597132\"}[$__interval],\n\"query_key\", 'delete from \"test_result_custom_field\" using (select \"test_result_custom_field\".\"test_result_id\", \"test_result_custom_field\".\"custom_field_value_id\" from \"test_result_custom_field\" where \"test_result_custom_field\".\"test_result_id\" IN KEYS except select \"v\".\"c1\", \"v\".\"c1\" from (VALUES (VAL))', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3931681995258587777\"}[$__interval],\n\"query_key\", 'BEGIN READ ONLY', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    },
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-1405798688416274133|-5963157192146902733|3758117993401091635|7482367936166775490|-7062684207193778685|3048459393875741712|-1876178204137927407|-8671219787684453336|-5596196383441054932|3829284484448228973\"}[$__interval],\n\"query_key\", 'select \"test_result\".\"id\", \"test_result\".\"local_run_uuid\" from \"test_result\" where (\"test_result\".\"id\" IN KEYS and \"test_result\".\"launch_id\" = $1 and \"test_result\".\"local_run_uuid\" is not null) order by \"test_result\".\"id\" for key share', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    }
   ]
  },
  {
   "title": "Stat per ($__interval) for : with \"tr_lk\" as (select \"test_result\".\"id\" from \"test_result\" where (\"test_result\".\"launch_id\" = $1 and \"test_result\".\"history_key\" IN KEYS) order by \"test_result\".\"id\" for no key update), \"tr_rt\" as (select \"test_result\".\"id\", first_value(\"test_result\".\"id\") over (partition by \"test_result\".\"history_key\" order by coalesce(\"test_result\".\"start\", \"test_result\".\"stop\", \"test_result\".\"created_date\") desc nulls last) as \"tr1\" from \"tr_lk\" join \"test_result\" on \"test_result\".\"id\" = \"tr_lk\".\"id\" order by \"test_result\".\"id\") update \"test_result\" set \"hidden\" = (\"test_result\".\"id\" <> \"tr_rt\".\"tr1\"), \"retried_by\" = case when \"test_result\".\"id\" <> \"tr_rt\".\"tr1\" then \"tr_rt\".\"tr1\" else cast($1 as bigint) end, \"last_modified_by\" = $1, \"last_modified_date\" = $1 from \"tr_rt\" where \"test_result\".\"id\" IN KEYS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3934084821068338370|-7629315488505523782|-9118850505870576616|-1407348636818196047|5343797223471241302|-1724946079165604596|-3314170056428998073|-5599554464466329331\"}[$__interval],\n\"query_key\", 'with \"tr_lk\" as (select \"test_result\".\"id\" from \"test_result\" where (\"test_result\".\"launch_id\" = $1 and \"test_result\".\"history_key\" IN KEYS) order by \"test_result\".\"id\" for no key update), \"tr_rt\" as (select \"test_result\".\"id\", first_value(\"test_result\".\"id\") over (partition by \"test_result\".\"history_key\" order by coalesce(\"test_result\".\"start\", \"test_result\".\"stop\", \"test_result\".\"created_date\") desc nulls last) as \"tr1\" from \"tr_lk\" join \"test_result\" on \"test_result\".\"id\" = \"tr_lk\".\"id\" order by \"test_result\".\"id\") update \"test_result\" set \"hidden\" = (\"test_result\".\"id\" <> \"tr_rt\".\"tr1\"), \"retried_by\" = case when \"test_result\".\"id\" <> \"tr_rt\".\"tr1\" then \"tr_rt\".\"tr1\" else cast($1 as bigint) end, \"last_modified_by\" = $1, \"last_modified_date\" = $1 from \"tr_rt\" where \"test_result\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 54 },
   "options": {
    "content": "with \"tr_lk\" as (select \"test_result\".\"id\" from \"test_result\" where (\"test_result\".\"launch_id\" = $1 and \"test_result\".\"history_key\" IN KEYS) order by \"test_result\".\"id\" for no key update), \"tr_rt\" as (select \"test_result\".\"id\", first_value(\"test_result\".\"id\") over (partition by \"test_result\".\"history_key\" order by coalesce(\"test_result\".\"start\", \"test_result\".\"stop\", \"test_result\".\"created_date\") desc nulls last) as \"tr1\" from \"tr_lk\" join \"test_result\" on \"test_result\".\"id\" = \"tr_lk\".\"id\" order by \"test_result\".\"id\") update \"test_result\" set \"hidden\" = (\"test_result\".\"id\" <> \"tr_rt\".\"tr1\"), \"retried_by\" = case when \"test_result\".\"id\" <> \"tr_rt\".\"tr1\" then \"tr_rt\".\"tr1\" else cast($1 as bigint) end, \"last_modified_by\" = $1, \"last_modified_date\" = $1 from \"tr_rt\" where \"test_result\".\"id\" IN KEYS"
   }
  },
  {
   "title": "Stat per ($__interval) for : update \"test_result\" set \"full_name\" = \"v\".\"c1\", \"description\" = \"v\".\"c1\", \"description_html\" = \"v\".\"c1\", \"precondition\" = \"v\".\"c1\", \"precondition_html\" = \"v\".\"c1\", \"expected_result\" = \"v\".\"c1\", \"expected_result_html\" = \"v\".\"c1\", \"test_layer_id\" = cast(\"v\".\"c1\" as bigint), \"manual\" = \"v\".\"c1\", \"status\" = \"v\".\"c1\", \"message\" = \"v\".\"c1\", \"trace\" = \"v\".\"c1\", \"start\" = cast(\"v\".\"c1\" as bigint), \"stop\" = cast(\"v\".\"c1\" as bigint), \"duration\" = cast(\"v\".\"c1\" as bigint), \"host_id\" = \"v\".\"c1\", \"thread_id\" = \"v\".\"c1\", \"local_run_uuid\" = \"v\".\"c1\" from (VALUES (VAL)) where \"test_result\".\"id\" = \"v\".\"c1\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-1890520225001541202|8541189628386284755|-6729167206932895045|-4956885308137481126|-7851074193500501429|8309675949422813515|-2562509008144719696|5387232704629596238|-5557594060599571491\"}[$__interval],\n\"query_key\", 'update \"test_result\" set \"full_name\" = \"v\".\"c1\", \"description\" = \"v\".\"c1\", \"description_html\" = \"v\".\"c1\", \"precondition\" = \"v\".\"c1\", \"precondition_html\" = \"v\".\"c1\", \"expected_result\" = \"v\".\"c1\", \"expected_result_html\" = \"v\".\"c1\", \"test_layer_id\" = cast(\"v\".\"c1\" as bigint), \"manual\" = \"v\".\"c1\", \"status\" = \"v\".\"c1\", \"message\" = \"v\".\"c1\", \"trace\" = \"v\".\"c1\", \"start\" = cast(\"v\".\"c1\" as bigint), \"stop\" = cast(\"v\".\"c1\" as bigint), \"duration\" = cast(\"v\".\"c1\" as bigint), \"host_id\" = \"v\".\"c1\", \"thread_id\" = \"v\".\"c1\", \"local_run_uuid\" = \"v\".\"c1\" from (VALUES (VAL)) where \"test_result\".\"id\" = \"v\".\"c1\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 62 },
   "options": {
    "content": "update \"test_result\" set \"full_name\" = \"v\".\"c1\", \"description\" = \"v\".\"c1\", \"description_html\" = \"v\".\"c1\", \"precondition\" = \"v\".\"c1\", \"precondition_html\" = \"v\".\"c1\", \"expected_result\" = \"v\".\"c1\", \"expected_result_html\" = \"v\".\"c1\", \"test_layer_id\" = cast(\"v\".\"c1\" as bigint), \"manual\" = \"v\".\"c1\", \"status\" = \"v\".\"c1\", \"message\" = \"v\".\"c1\", \"trace\" = \"v\".\"c1\", \"start\" = cast(\"v\".\"c1\" as bigint), \"stop\" = cast(\"v\".\"c1\" as bigint), \"duration\" = cast(\"v\".\"c1\" as bigint), \"host_id\" = \"v\".\"c1\", \"thread_id\" = \"v\".\"c1\", \"local_run_uuid\" = \"v\".\"c1\" from (VALUES (VAL)) where \"test_result\".\"id\" = \"v\".\"c1\""
   }
  },
  {
   "title": "Stat per ($__interval) for : insert into \"test_result_scenario_block\" (\"test_result_id\", \"data\", \"created_by\", \"created_date\", \"last_modified_by\", \"last_modified_date\") select \"v\".\"c1\", \"v\".\"c1\", $1, $1, $1, $1 from (VALUES (VAL)) do update set \"data\" = \"excluded\".\"data\", \"last_modified_by\" = $1, \"last_modified_date\" = $1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"5440757910167813368|-2754656615418654773|4447347532761596015|-4985950084870127777|4066338591555528632|2783677633027607696|3306178492070608084|3224420977893184079\"}[$__interval],\n\"query_key\", 'insert into \"test_result_scenario_block\" (\"test_result_id\", \"data\", \"created_by\", \"created_date\", \"last_modified_by\", \"last_modified_date\") select \"v\".\"c1\", \"v\".\"c1\", $1, $1, $1, $1 from (VALUES (VAL)) do update set \"data\" = \"excluded\".\"data\", \"last_modified_by\" = $1, \"last_modified_date\" = $1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 70 },
   "options": {
    "content": "insert into \"test_result_scenario_block\" (\"test_result_id\", \"data\", \"created_by\", \"created_date\", \"last_modified_by\", \"last_modified_date\") select \"v\".\"c1\", \"v\".\"c1\", $1, $1, $1, $1 from (VALUES (VAL)) do update set \"data\" = \"excluded\".\"data\", \"last_modified_by\" = $1, \"last_modified_date\" = $1"
   }
  },
  {
   "title": "Stat per ($__interval) for : insert into \"test_result\" (\"launch_id\", \"test_session_id\", \"job_run_id\", \"id\", \"test_case_id\", \"name\", \"history_key\", \"hidden\", \"external\", \"created_by\", \"created_date\", \"last_modified_by\", \"last_modified_date\") VALUES (VAL) do update set \"launch_id\" = \"excluded\".\"launch_id\", \"test_session_id\" = \"excluded\".\"test_session_id\", \"job_run_id\" = \"excluded\".\"job_run_id\", \"test_case_id\" = \"excluded\".\"test_case_id\", \"name\" = \"excluded\".\"name\", \"history_key\" = \"excluded\".\"history_key\", \"hidden\" = $1, \"external\" = $1, \"last_modified_by\" = $1, \"last_modified_date\" = $1 returning \"test_result\".\"id\", \"test_result\".\"test_case_id\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"354776470543819834|-2013418728145581168|-5941973755437388416|-1138148854663917314|-6151010435157117400|1504231528310994426|6771795209721327702|8264927604351288767|1031709803157834306\"}[$__interval],\n\"query_key\", 'insert into \"test_result\" (\"launch_id\", \"test_session_id\", \"job_run_id\", \"id\", \"test_case_id\", \"name\", \"history_key\", \"hidden\", \"external\", \"created_by\", \"created_date\", \"last_modified_by\", \"last_modified_date\") VALUES (VAL) do update set \"launch_id\" = \"excluded\".\"launch_id\", \"test_session_id\" = \"excluded\".\"test_session_id\", \"job_run_id\" = \"excluded\".\"job_run_id\", \"test_case_id\" = \"excluded\".\"test_case_id\", \"name\" = \"excluded\".\"name\", \"history_key\" = \"excluded\".\"history_key\", \"hidden\" = $1, \"external\" = $1, \"last_modified_by\" = $1, \"last_modified_date\" = $1 returning \"test_result\".\"id\", \"test_result\".\"test_case_id\"', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 78 },
   "options": {
    "content": "insert into \"test_result\" (\"launch_id\", \"test_session_id\", \"job_run_id\", \"id\", \"test_case_id\", \"name\", \"history_key\", \"hidden\", \"external\", \"created_by\", \"created_date\", \"last_modified_by\", \"last_modified_date\") VALUES (VAL) do update set \"launch_id\" = \"excluded\".\"launch_id\", \"test_session_id\" = \"excluded\".\"test_session_id\", \"job_run_id\" = \"excluded\".\"job_run_id\", \"test_case_id\" = \"excluded\".\"test_case_id\", \"name\" = \"excluded\".\"name\", \"history_key\" = \"excluded\".\"history_key\", \"hidden\" = $1, \"external\" = $1, \"last_modified_by\" = $1, \"last_modified_date\" = $1 returning \"test_result\".\"id\", \"test_result\".\"test_case_id\""
   }
  },
  {
   "title": "Stat per ($__interval) for : insert into \"test_result_custom_field\" (\"test_result_id\", \"custom_field_value_id\") select \"v\".\"c1\", \"v\".\"c1\" from (VALUES (VAL)) do nothing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"6973423874184579389|1931361531336001837|6134564063525871934|892735712321394778|-6454084909132048456|-6267104841689983545|800169189322848841|1835519071896069564|-5670520736262774960|7289690819468492297|-719898416793592636|-3171469207843903637|6656928851985625580|-4532199773036126758|5246163688087098552|7856500316668066297\"}[$__interval],\n\"query_key\", 'insert into \"test_result_custom_field\" (\"test_result_id\", \"custom_field_value_id\") select \"v\".\"c1\", \"v\".\"c1\" from (VALUES (VAL)) do nothing', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 86 },
   "options": {
    "content": "insert into \"test_result_custom_field\" (\"test_result_id\", \"custom_field_value_id\") select \"v\".\"c1\", \"v\".\"c1\" from (VALUES (VAL)) do nothing"
   }
  },
  {
   "title": "Stat per ($__interval) for : update \"launch\" set \"last_modified_date\" = $1, \"last_modified_by\" = $1 where \"launch\".\"id\" = $1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"1157584214810043055\"}[$__interval],\n\"query_key\", 'update \"launch\" set \"last_modified_date\" = $1, \"last_modified_by\" = $1 where \"launch\".\"id\" = $1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 94 },
   "options": {
    "content": "update \"launch\" set \"last_modified_date\" = $1, \"last_modified_by\" = $1 where \"launch\".\"id\" = $1"
   }
  },
  {
   "title": "Stat per ($__interval) for : update \"test_result\" set \"scenario_key\" = $1, \"last_modified_by\" = $1, \"last_modified_date\" = $1 where \"test_result\".\"id\" IN KEYS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-5961531816685115219|5348561853148171200|-2024315525205880296|-3946352109319617114|-7114134203024639928|3857573856810294698|4696212443935485341|3243486293748510443\"}[$__interval],\n\"query_key\", 'update \"test_result\" set \"scenario_key\" = $1, \"last_modified_by\" = $1, \"last_modified_date\" = $1 where \"test_result\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 102 },
   "options": {
    "content": "update \"test_result\" set \"scenario_key\" = $1, \"last_modified_by\" = $1, \"last_modified_date\" = $1 where \"test_result\".\"id\" IN KEYS"
   }
  },
  {
   "title": "Stat per ($__interval) for : with \"exp_tr1\" as (select distinct on (\"v\".\"c1\") \"v\".\"c1\", \"test_result\".\"id\" from \"test_result\" join (VALUES (VAL)) select \"exp_tr1\".\"c1\", \"test_result\".\"id\" from \"test_result\" join \"exp_tr1\" on \"test_result\".\"id\" = \"exp_tr1\".\"id\" order by \"test_result\".\"id\" for no key update skip locked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-3065101627323191925|6172012046876450672|-154770314165353031|-4713854124755418034|-5345628697385564956|-4444445086239616450|8288715177846116362|-5728658692971845333|4285799337526335392\"}[$__interval],\n\"query_key\", 'with \"exp_tr1\" as (select distinct on (\"v\".\"c1\") \"v\".\"c1\", \"test_result\".\"id\" from \"test_result\" join (VALUES (VAL)) select \"exp_tr1\".\"c1\", \"test_result\".\"id\" from \"test_result\" join \"exp_tr1\" on \"test_result\".\"id\" = \"exp_tr1\".\"id\" order by \"test_result\".\"id\" for no key update skip locked', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 110 },
   "options": {
    "content": "with \"exp_tr1\" as (select distinct on (\"v\".\"c1\") \"v\".\"c1\", \"test_result\".\"id\" from \"test_result\" join (VALUES (VAL)) select \"exp_tr1\".\"c1\", \"test_result\".\"id\" from \"test_result\" join \"exp_tr1\" on \"test_result\".\"id\" = \"exp_tr1\".\"id\" order by \"test_result\".\"id\" for no key update skip locked"
   }
  },
  {
   "title": "Stat per ($__interval) for : select bool_and(exists (with \"up_cte\" as (((select distinct \"permission_permission_set\".\"permission\" from \"group_project_access\" join \"access_group\" on \"group_project_access\".\"group_id\" = \"access_group\".\"id\" join \"group_user\" on \"group_user\".\"group_id\" = \"access_group\".\"id\" join \"permission_permission_set\" on \"permission_permission_set\".\"permission_set_id\" = \"group_project_access\".\"permission_set_id\" where (\"group_project_access\".\"project_id\" = \"project\".\"id\" and \"group_user\".\"username\" = $1 and (\"access_group\".\"personal\" = $1 or (\"access_group\".\"personal\" = $1 and \"access_group\".\"name\" = $1)))) union all (select \"v\".\"c1\" from (VALUES (VAL)) from \"project\" where \"project\".\"id\" IN KEYS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-8946200807776987162|-9200057509331791363|-8063467946522176185|435219297541885788|-3665261003842485834|8252378364890499554|-5024892381980960465\"}[$__interval],\n\"query_key\", 'select bool_and(exists (with \"up_cte\" as (((select distinct \"permission_permission_set\".\"permission\" from \"group_project_access\" join \"access_group\" on \"group_project_access\".\"group_id\" = \"access_group\".\"id\" join \"group_user\" on \"group_user\".\"group_id\" = \"access_group\".\"id\" join \"permission_permission_set\" on \"permission_permission_set\".\"permission_set_id\" = \"group_project_access\".\"permission_set_id\" where (\"group_project_access\".\"project_id\" = \"project\".\"id\" and \"group_user\".\"username\" = $1 and (\"access_group\".\"personal\" = $1 or (\"access_group\".\"personal\" = $1 and \"access_group\".\"name\" = $1)))) union all (select \"v\".\"c1\" from (VALUES (VAL)) from \"project\" where \"project\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 118 },
   "options": {
    "content": "select bool_and(exists (with \"up_cte\" as (((select distinct \"permission_permission_set\".\"permission\" from \"group_project_access\" join \"access_group\" on \"group_project_access\".\"group_id\" = \"access_group\".\"id\" join \"group_user\" on \"group_user\".\"group_id\" = \"access_group\".\"id\" join \"permission_permission_set\" on \"permission_permission_set\".\"permission_set_id\" = \"group_project_access\".\"permission_set_id\" where (\"group_project_access\".\"project_id\" = \"project\".\"id\" and \"group_user\".\"username\" = $1 and (\"access_group\".\"personal\" = $1 or (\"access_group\".\"personal\" = $1 and \"access_group\".\"name\" = $1)))) union all (select \"v\".\"c1\" from (VALUES (VAL)) from \"project\" where \"project\".\"id\" IN KEYS"
   }
  },
  {
   "title": "Stat per ($__interval) for : select distinct \"test_result\".\"id\", \"test_result\".\"name\", \"test_result\".\"status\", \"test_result\".\"start\", \"test_result\".\"stop\", \"test_result\".\"duration\", \"test_result\".\"manual\", \"test_result\".\"assignee\", \"test_result\".\"tested_by\", \"test_result\".\"test_case_id\", \"test_layer\".\"name\", -(\"test_result\".\"status\") from \"test_result\" left outer join \"test_layer\" on \"test_result\".\"test_layer_id\" = \"test_layer\".\"id\" where (\"test_result\".\"launch_id\" = $1 and \"test_result\".\"hidden\" = $1 and $1) order by \"test_result\".\"test_case_id\" asc limit $1 offset $1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-1416140981673074347\"}[$__interval],\n\"query_key\", 'select distinct \"test_result\".\"id\", \"test_result\".\"name\", \"test_result\".\"status\", \"test_result\".\"start\", \"test_result\".\"stop\", \"test_result\".\"duration\", \"test_result\".\"manual\", \"test_result\".\"assignee\", \"test_result\".\"tested_by\", \"test_result\".\"test_case_id\", \"test_layer\".\"name\", -(\"test_result\".\"status\") from \"test_result\" left outer join \"test_layer\" on \"test_result\".\"test_layer_id\" = \"test_layer\".\"id\" where (\"test_result\".\"launch_id\" = $1 and \"test_result\".\"hidden\" = $1 and $1) order by \"test_result\".\"test_case_id\" asc limit $1 offset $1', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 126 },
   "options": {
    "content": "select distinct \"test_result\".\"id\", \"test_result\".\"name\", \"test_result\".\"status\", \"test_result\".\"start\", \"test_result\".\"stop\", \"test_result\".\"duration\", \"test_result\".\"manual\", \"test_result\".\"assignee\", \"test_result\".\"tested_by\", \"test_result\".\"test_case_id\", \"test_layer\".\"name\", -(\"test_result\".\"status\") from \"test_result\" left outer join \"test_layer\" on \"test_result\".\"test_layer_id\" = \"test_layer\".\"id\" where (\"test_result\".\"launch_id\" = $1 and \"test_result\".\"hidden\" = $1 and $1) order by \"test_result\".\"test_case_id\" asc limit $1 offset $1"
   }
  },
  {
   "title": "Stat per ($__interval) for : delete from \"result_file_key\" where \"result_file_key\".\"id\" IN KEYS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(\nlabel_replace(\npg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\", queryid=~\"-81176439872564081|17670673547066367|1545784804722760381|-4488997511127977649|3958803941604940321|-3950490104272315063|-9174957291846684074|2956845977626877848|2624756295929383646|-4864816528718272866\"}[$__interval],\n\"query_key\", 'delete from \"result_file_key\" where \"result_file_key\".\"id\" IN KEYS', \"datname\", \".*\")\n)) by (query_key)",
     "legendFormat": "{{query_key}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 134 },
   "options": {
    "content": "delete from \"result_file_key\" where \"result_file_key\".\"id\" IN KEYS"
   }
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 } },
  {
   "title": "Total error events - [$RDS]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 143 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "stats count() by bin(1m)\n| filter @message like /(?i)(\\:error\\:|\\:fatal\\:)/",
     "logGroupNames": [
      "/aws/rds/instance/$RDS/postgresql"
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "Version - [$RDS]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(pg_settings_server_version_num{miro_rds_cluster=\"$RDS_name\"}/10000)+round(pg_settings_server_version_num{miro_rds_cluster=\"$RDS_name\"}%10000/100)/100+pg_settings_server_version_num{miro_rds_cluster=\"$RDS_name\"}%100/100",
     "legendFormat": "version"
    }
   ]
  },
  {
   "title": "Database size - [$RDS]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.99, \navg(pg_stat_activity_active_connections_connection_query_time_sec{miro_rds_cluster=\"$RDS_name\",connection_backend_type=\"client backend\",connection_state!=\"idle\"})[$__rate_interval]) > 0",
     "legendFormat": "Query response time, p99",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Useful links",
   "type": "text",
   "description": "Note that Performance Insights takes some time to load, so Performance Insights will typically remain blank for a few seconds before displaying any information.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 143 },
   "options": {
    "content": "* AWS Performance Insights for [__${RDS_name}__](https://eu-west-1.console.aws.amazon.com/rds/home?region=$region#performance-insights-v20206:/resourceId/$rds_instance_resource_id/resourceName/$RDS_name/presetKey/1h/presetAmount/1/presetUnit/hour/startTime/$__from/endTime/$__to)\n* AWS CloudWatch Logs Insights for RDS [__${RDS_name}__](https://$region.console.aws.amazon.com/cloudwatch/home?region=$region#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-3600~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2020~source~(~'arn*3aaws*3alogs*3a$region*3a543998612913*3alog-group*3a*2faws*2frds*2finstance*2f$RDS_name*2fpostgresql)))\n* AWS CloudWatch Logs Insights for RDS Proxy [__${RDS_Proxy}__](https://$region.console.aws.amazon.com/cloudwatch/home?region=$region#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-3600~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2020~source~(~'arn*3aaws*3alogs*3a$region*3a543998612913*3alog-group*3a*2faws*2frds*2fproxy*2f$RDS_name-proxy)))\n* [__EU region__] Alertmanager Silences for [__${RDS_name}__](https://alertmanager.svc.miro.com/#/silences?silenced=false&inhibited=false&active=true&filter=%7Bmiro_rds_cluster_deployment%3D%22$RDS_name%22%7D)\n* [__US region__] Alertmanager Silences for [__${RDS_name}__](https://alertmanager.svc.us.miro.com/#/silences?silenced=false&inhibited=false&active=true&filter=%7Bmiro_rds_cluster_deployment%3D%22$RDS_name%22%7D)\n\n### Database info:\n* RDS name: `${RDS_name}`\n* url: `${rds_url}/${database}`"
   }
  },
  {
   "title": "Error patterns - [$RDS]",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "fields @message\n| filter @message like /(?i)(\\:error\\:|\\:fatal\\:)/ | pattern @message",
     "logGroupNames": [
      "/aws/rds/instance/$RDS/postgresql"
     ],
     "queryMode": "Logs",
     "region": "$region"
    }
   ]
  },
  { "title": "RDS [$RDS]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "DBLoad,  Average active sessions [$RDS_name]",
   "type": "timeseries",
   "description": "* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.Cloudwatch.html\n* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.Overview.ActiveSessions.html",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "DBLoadNonCPU",
     "expression": "MAX(FILL(SEARCH('{AWS/RDS,DBInstanceIdentifier} DBInstanceIdentifier=\"$RDS_name\" MetricName=\"DBLoadNonCPU\"', 'Average'),0))",
     "id": "e1",
     "metricEditorMode": 1,
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "alias": "DBLoadCPU",
     "expression": "MAX(FILL(SEARCH('{AWS/RDS,DBInstanceIdentifier} DBInstanceIdentifier=\"$RDS_name\" MetricName=\"DBLoadCPU\"', 'Average'),0))",
     "id": "e2",
     "metricEditorMode": 1,
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "alias": "max vCPU",
     "expression": "DB_PERF_INSIGHTS('RDS', '$rds_instance_resource_id', ['os.general.numVCPUs.avg'])",
     "id": "e3",
     "metricEditorMode": 1,
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "alias": "DBLoadTotal",
     "expression": "MAX(FILL(SEARCH('{AWS/RDS,DBInstanceIdentifier} DBInstanceIdentifier=\"$RDS_name\" MetricName=\"DBLoad\"', 'Average'),0))",
     "id": "e6",
     "metricEditorMode": 1,
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "TPS [$database] - [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{miro_rds_cluster=\"$RDS_name\"}[$__rate_interval])) by(miro_rds_cluster)",
     "legendFormat": "{{miro_rds_cluster}}"
    },
    {
     "expr": "job:pg_stat_database_xact_commit_rollback:rate5m_prediction{miro_rds_cluster=\"$RDS_name\"}*1.5",
     "legendFormat": "prediction_max"
    },
    {
     "expr": "job:pg_stat_database_xact_commit_rollback:rate5m_prediction{miro_rds_cluster=\"$RDS_name\"}/2",
     "legendFormat": "prediction_min"
    }
   ]
  },
  {
   "title": "Errors - ($RDS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 151 },
   "targets": [
    {
     "expression": "stats count() by bin(1m)\n| filter @message like /(?i)(\\:error\\:|\\:fatal\\:)/",
     "logGroupNames": [
      "/aws/rds/instance/$RDS/postgresql"
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "Network throughput [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$RDS" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$RDS" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Wait events, top 10 [$database]",
   "type": "timeseries",
   "description": "* https://www.postgresql.org/docs/15/monitoring-stats.html#WAIT-EVENT-TABLE",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,increase(pg_stat_activity_waits_count{miro_rds_cluster=\"$RDS_name\",wait!=\"Client:ClientRead\"}[$__interval]) > 0)",
     "legendFormat": "{{ wait }}"
    }
   ]
  },
  {
   "title": "Buffer Cache Ratio [$database] - [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(pg_stat_database_blks_hit{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}[$__rate_interval]) / (rate(pg_stat_database_blks_hit{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}[$__rate_interval]) + rate(pg_stat_database_blks_read{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}[$__rate_interval]))) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Memory usage, Bytes [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$RDS" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk IOPS [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$RDS" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$RDS" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU utilization, % [$RDS_name]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "os.cpuUtilization.steal",
     "expression": "FIRST(SLICE(e1, 0, 1))",
     "id": "e2",
     "metricEditorMode": 1,
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "os.cpuUtilization.guest",
     "expression": "FIRST(SLICE(e1, 1, 2))",
     "id": "e3",
     "metricEditorMode": 1,
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "os.cpuUtilization.irq",
     "expression": "FIRST(SLICE(e1, 2, 3))",
     "id": "e4",
     "metricEditorMode": 1,
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "os.cpuUtilization.wait",
     "expression": "FIRST(SLICE(e1, 3, 4))",
     "id": "e5",
     "metricEditorMode": 1,
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "os.cpuUtilization.user",
     "expression": "FIRST(SLICE(e1, 4, 5))",
     "id": "e6",
     "metricEditorMode": 1,
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "os.cpuUtilization.system",
     "expression": "FIRST(SLICE(e1, 5, 6))",
     "id": "e7",
     "metricEditorMode": 1,
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "os.cpuUtilization.nice",
     "expression": "FIRST(SLICE(e1, 6, 7))",
     "id": "e8",
     "metricEditorMode": 1,
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Queue [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$RDS" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Connections utilization, % [$database]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{miro_rds_cluster=\"$RDS_name\"}) / min(pg_settings_max_connections{miro_rds_cluster=\"$RDS_name\"})",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Temp files [$database] - [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase(pg_stat_database_temp_files{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}[$__rate_interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Locks [$database] - [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_locks_count{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}) by(mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Tuples: Reads (Tuples per seconds) [$database]",
   "type": "timeseries",
   "description": "The `tup_returned` metric shows the number of rows read. The `tup_fetched` metric shows the number of rows returned to the client. If `tup_returned` is significantly larger than `tup_fetched`, the data might not be properly indexed. Also, your table statistics might not be current.\n* `tup_returned ` - Number of live rows fetched by sequential scans and index entries returned by index scans in this database\n* `tup_fetched` - Number of live rows fetched by index scans in this database\n* Documentation: https://www.postgresql.org/docs/15/monitoring-stats.html#MONITORING-PG-STAT-DATABASE-VIEW",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{miro_rds_cluster=\"$RDS_name\",datname=\"$database\",relname!~\"pg_.*\"}[$__rate_interval])",
     "legendFormat": "tup_fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{miro_rds_cluster=\"$RDS_name\",datname=\"$database\",relname!~\"pg_.*\"}[$__rate_interval])",
     "legendFormat": "tup_returned"
    }
   ]
  },
  {
   "title": "Read/Write Latency [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$RDS" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$RDS" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Temp files size, bytes [$database] - [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(pg_stat_database_temp_bytes{miro_rds_instance_name=\"$RDS\",datname=\"$database\"}[$__rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "QPS (top 10)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_statements_calls{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}} (user: {{user}})"
    }
   ]
  },
  {
   "title": "Top 5 queries by time consumed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(5,rate(pg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}[$__rate_interval]))/sum(rate(pg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}[$__rate_interval]))",
     "legendFormat": "{{queryid}} (user: {{user}})"
    }
   ]
  },
  {
   "title": "[WIP] Blocked queries [$database]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 187 },
   "targets": [
    {
     "expr": "sum_over_time(pg_blocked_queries{miro_rds_cluster=\"$RDS_name\"}[$__interval])",
     "legendFormat": "[{{table}}] => {{blocking_statement}}({{pid}})"
    },
    {
     "expr": "pg_blocked_queries{miro_rds_cluster=\"$RDS_name\"}",
     "legendFormat": "[{{table}}] => {{blocking_statement}}({{pid}})"
    }
   ]
  },
  {
   "title": "Free storage space, Bytes [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$RDS" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DML [$database]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_del{miro_rds_cluster=\"$RDS_name\",datname=\"$database\",relname!~\"pg_.*\"}[$__rate_interval])",
     "legendFormat": "{{ relname }} - del"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_upd{miro_rds_cluster=\"$RDS_name\",datname=\"$database\",relname!~\"pg_.*\"}[$__rate_interval])",
     "legendFormat": "{{ relname }} - upd"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_ins{miro_rds_cluster=\"$RDS_name\",datname=\"$database\",relname!~\"pg_.*\"}[$__rate_interval])",
     "legendFormat": "{{ relname }} - ins"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_hot_upd{miro_rds_cluster=\"$RDS_name\",datname=\"$database\",relname!~\"pg_.*\"}[$__rate_interval])",
     "legendFormat": "{{ relname }} - hot upd"
    }
   ]
  },
  {
   "title": "Buffers written ($RDS_name)",
   "type": "timeseries",
   "description": "* `buffers_clean` and `buffers_backend` show number of buffers cleaned by bgwriter and postgres’ backends respectively – `buffers_clean` should be greater than `buffers_backend`. Otherwise, you should increase `bgwriter_lru_multiplier` and decrease `bgwriter_delay`. Note, it also may be a sign that you have insufficient shared buffers and hot part of your data don’t fit into shared buffers and forced to travel between RAM and disks.\n`buffers_checkpoint` - show number of buffers written during checkpoints\n- Documentation: \n- https://www.postgresql.org/docs/15/monitoring-stats.html#MONITORING-PG-STAT-BGWRITER-VIEW\n- https://dataegret.com/2017/03/deep-dive-into-postgres-stats-pg_stat_bgwriter/",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(pg_stat_bgwriter_buffers_checkpoint{miro_rds_cluster=\"$RDS_name\"}[$__rate_interval])*8192",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "increase(pg_stat_bgwriter_buffers_backend{miro_rds_cluster=\"$RDS_name\"}[$__rate_interval])*8192",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "increase(pg_stat_bgwriter_buffers_clean{miro_rds_cluster=\"$RDS_name\"}[$__rate_interval])*8192",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Total relation size, bytes [$database]",
   "type": "graph",
   "description": "including indexes, etc",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 196 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_total_relation_size_bytes{miro_rds_cluster=\"$RDS_name\"}",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "WAL Usage, Bytes [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$RDS" },
     "metricName": "TransactionLogsDiskUsage",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Transaction IDs utilization [$database]",
   "type": "timeseries",
   "description": "* A transaction ID is assigned when the transaction starts, and it's frozen until the transaction is vacuumed. Transaction ID utilization is the number of unvacuumed transactions expressed as a fraction of the maximum value of `autovacuum_freeze_max_age`. If the transaction ID utilization trends towards very high values (80% or more), the database might be at risk of transaction ID exhaustion. Transaction ID utilization reaching 100% is termed as transaction ID wraparound. Once the transaction ID utilization percentage reaches 100%, PostgreSQL stops accepting write queries.\n* https://www.postgresql.org/docs/current/transaction-id.html",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(max(pg_database_xid_age{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}) by(datname))\n/ on(miro_rds_cluster) group_left max(pg_settings_autovacuum_freeze_max_age{miro_rds_cluster=\"$RDS_name\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Sessions activity, seconds [$database] - [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(max_over_time(pg_stat_activity_max_tx_duration{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}[$__rate_interval])) by(state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Number of connection types [$database]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{miro_rds_cluster=\"$RDS_name\"})",
     "legendFormat": "numbackends [total]"
    },
    {
     "expr": "sum(pg_stat_activity_count{miro_rds_cluster=\"$RDS_name\"}) by (state,datname) != 0",
     "legendFormat": "{{state}} [{{datname}}]"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_stat_bgwriter_checkpoints_req{miro_rds_cluster=\"$RDS_name\"}[$__rate_interval]) + increase(pg_stat_bgwriter_checkpoints_timed{miro_rds_cluster=\"$RDS_name\"}[$__rate_interval])",
     "legendFormat": "checkpoint"
    }
   ]
  },
  {
   "title": "PostgresExporter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_exporter_last_scrape_duration_seconds{miro_rds_cluster=\"$RDS_name\"} or pg_exporter_last_scrape_duration_seconds{service=\"$RDS_name\"}",
     "legendFormat": "scrape_duration"
    }
   ]
  },
  {
   "title": "Active query execution time, s - [$RDS]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 212 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10,pg_stat_activity_active_connections_connection_query_time_sec{miro_rds_cluster=\"$RDS_name\",connection_backend_type=\"client backend\",connection_state!=\"idle\"})",
     "legendFormat": "[{{pid}}] {{query}} - {{connection_state}}"
    }
   ]
  },
  {
   "title": "Deadlocks [$database]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_deadlocks{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}[$__rate_interval])) by(datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Dead tuples [$database]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, pg_stat_user_tables_n_dead_tup{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"})",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Missing metrics [$RDS_name]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "absent(pg_up{miro_rds_cluster=\"$RDS_name\"}) or 0",
     "legendFormat": "missed"
    }
   ]
  },
  {
   "title": "Scrape errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_exporter_last_scrape_error{miro_rds_cluster=\"$RDS_name\"} or pg_exporter_last_scrape_error{service=\"$RDS_name\"}",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "\"$database\" data distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 220 },
   "targets": [
    {
     "expr": "sum(max(pg_total_relation_size_bytes{dmiro_rds_cluster=\"$RDS_name\",schemaname!~\"(pg_catalog|pg_toast|information_schema)\"}) by (schemaname, relname)) by (schemaname, relname)"
    },
    {
     "expr": "sum(max(pg_total_relation_size_bytes{miro_rds_cluster=\"$RDS_name\",schemaname!~\"(pg_catalog|pg_toast|information_schema)\"}) by (schemaname, relname)) by (schemaname, relname) /\n sum(max(pg_total_relation_size_bytes{miro_rds_cluster=\"$RDS_name\",schemaname!~\"(pg_catalog|pg_toast|information_schema)\"}) by (schemaname, relname))"
    },
    {
     "expr": "sum(max(pg_stat_user_tables_n_live_tup{miro_rds_cluster=\"$RDS_name\",schemaname!~\"(pg_catalog|pg_toast|information_schema)\"}) by (schemaname, relname)) by (schemaname, relname) "
    },
    {
     "expr": "sum(max(pg_total_relation_size_bytes{miro_rds_cluster=\"$RDS_name\",schemaname!~\"(pg_catalog|pg_toast|information_schema)\"}) by (schemaname, relname)) by (schemaname, relname) / \nsum(max(pg_stat_user_tables_n_live_tup{miro_rds_cluster=\"$RDS_name\",schemaname!~\"(pg_catalog|pg_toast|information_schema)\"}) by (schemaname, relname)) by (schemaname, relname) "
    },
    {
     "expr": "sum(max(pg_stat_user_tables_n_dead_tup{miro_rds_cluster=\"$RDS_name\",schemaname!~\"(pg_catalog|pg_toast|information_schema)\"}) by (schemaname, relname)) by (schemaname, relname)"
    }
   ]
  },
  {
   "title": "Invalid indexes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(pg_indexes_invalid_count{miro_rds_cluster=\"$RDS_name\"} and on (miro_rds_cluster) pg_stat_activity_active_connections_connection_backend_lifetime_sec{application_name=\"pg_repack\"} == 0) or 0",
     "legendFormat": "{{schemaname}}.{{indexname}}"
    }
   ]
  },
  {
   "title": "CloudWatch Logs usage, Bytes [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "postgresql.log",
     "dimensions": {
      "LogGroupName": "/aws/rds/instance/$RDS/postgresql"
     },
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "period": "15m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "[WIP] Autovacuum workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 228 },
   "targets": [
    {
     "expr": "pg_autovacuum_count_av_workers{nmiro_rds_cluster=\"$RDS_name\"}",
     "legendFormat": "autovacuum"
    },
    {
     "expr": "pg_autovacuum_count_av_wrap{miro_rds_cluster=\"$RDS_name\"}",
     "legendFormat": "wraparound"
    },
    {
     "expr": "pg_autovacuum_count_v_manual{miro_rds_cluster=\"$RDS_name\"}",
     "legendFormat": "manual"
    },
    {
     "expr": "pg_settings_autovacuum_max_workers{miro_rds_cluster=\"$RDS_name\"}",
     "legendFormat": "autovacuum_max_workers"
    }
   ]
  },
  {
   "title": "Vacuum count per table [$database]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_vacuum_count{miro_rds_cluster=\"$RDS_name\",datname=\"$database\"}[$__rate_interval])",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": " Connections (DB + Client + Pinned)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 236 },
   "targets": [
    {
     "alias": "DatabaseConnections_Sum",
     "expression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"DatabaseConnections\"', 'Sum'),0)",
     "metricEditorMode": 1,
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"DatabaseConnections\"', 'Sum'),0)",
     "statistic": "Sum"
    },
    {
     "alias": "DatabaseConnectionsCurrentlySessionPinned_Sum",
     "expression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"DatabaseConnectionsCurrentlySessionPinned\"', 'Sum'),0)",
     "metricEditorMode": 1,
     "metricName": "DatabaseConnectionsCurrentlySessionPinned",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "ClientConnections_Sum",
     "expression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"ClientConnections\"', 'Sum'),0)",
     "metricEditorMode": 1,
     "metricName": "ClientConnections",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "MaxDatabaseConnectionsAllowed_Sum",
     "expression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"MaxDatabaseConnectionsAllowed\"', 'Sum'),0)",
     "metricEditorMode": 1,
     "metricName": "MaxDatabaseConnectionsAllowed",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "DatabaseConnectionsSetupFailed_Sum",
     "expression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"DatabaseConnectionsSetupFailed\"', 'Sum'),0)",
     "metricEditorMode": 1,
     "metricName": "DatabaseConnectionsSetupFailed",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Replication lag [$database] - [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 236 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_replication_info_bytes_pending{miro_rds_cluster=\"$RDS_name\"}+pg_replication_info_bytes_write_lsn_diff{miro_rds_cluster=\"$RDS_name\"}+pg_replication_info_bytes_flush_lsn_diff{miro_rds_cluster=\"$RDS_name\"}+pg_replication_info_bytes_replay_lsn_diff{miro_rds_cluster=\"$RDS_name\"}",
     "legendFormat": "lag"
    },
    {
     "expr": "pg_replication_info_bytes_pending{miro_rds_cluster=\"$RDS_name\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "pg_replication_info_bytes_write_lsn_diff{miro_rds_cluster=\"$RDS_name\"}",
     "legendFormat": "write"
    },
    {
     "expr": "pg_replication_info_bytes_flush_lsn_diff{miro_rds_cluster=\"$RDS_name\"}",
     "legendFormat": "flush"
    },
    {
     "expr": "pg_replication_info_bytes_replay_lsn_diff{miro_rds_cluster=\"$RDS_name\"}",
     "legendFormat": "replay"
    }
   ]
  },
  {
   "title": "[WIP] Resource usage by all queries [$database] - [$RDS]",
   "type": "timeseries",
   "description": "- https://www.postgresql.org/docs/current/monitoring-stats.html#WAIT-EVENT-TABLE",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 236 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_seconds_total{miro_rds_cluster=\"$RDS_name\"}[$__rate_interval])) - sum(sum(rate(pg_stat_statements_block_read_seconds_total{miro_rds_cluster=\"$RDS_name\"}[$__rate_interval])) + sum(rate(pg_stat_statements_block_write_seconds_total{miro_rds_cluster=\"$RDS_name\"}[$__rate_interval])))",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(rate(pg_stat_statements_block_write_seconds_total{miro_rds_cluster=\"$RDS_name\"}[$__rate_interval]))",
     "legendFormat": "IO writes"
    },
    {
     "expr": "sum(rate(pg_stat_statements_block_read_seconds_total{miro_rds_cluster=\"$RDS_name\"}[$__rate_interval]))",
     "legendFormat": "IO reads"
    }
   ]
  },
  { "title": "RDS Proxy [$RDS_Proxy]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 244 } },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 245 },
   "options": {
    "content": "# RDS Proxy metrics\n\n* __DatabaseConnectionsBorrowLatency__ - The time in microseconds that it takes for the proxy being monitored to get a database connection. \n* __QueryDatabaseResponseLatency__ - The time in microseconds that the database took to respond to the query.\n* __QueryResponseLatency__ - The time in microseconds between getting a query request and the proxy responding to it."
   }
  },
  {
   "title": "ConnectionsLatency [$RDS_Proxy]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 245 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "DatabaseConnectionsBorrowLatency_Average",
     "dimensions": { "ProxyName": "$RDS_Proxy" },
     "expression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"DatabaseConnectionsBorrowLatency\"', 'Average'),0)",
     "metricEditorMode": 1,
     "metricName": "DatabaseConnectionsBorrowLatency",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "QueryResponseLatency_Average",
     "dimensions": { "ProxyName": "$RDS_Proxy" },
     "expression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"QueryResponseLatency\"', 'Average'),0)",
     "metricEditorMode": 1,
     "metricName": "QueryResponseLatency",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "QueryDatabaseResponseLatency_Average",
     "dimensions": { "ProxyName": "$RDS_Proxy" },
     "expression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"QueryDatabaseResponseLatency\"', 'Average'),0)",
     "metricEditorMode": 1,
     "metricName": "QueryDatabaseResponseLatency",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "[$RDS_Proxy] MaxDatabaseConnectionsAllowed Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 245 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "utilization",
     "expression": "MAX(FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"DatabaseConnections\"','Sum'),0))\n/\nMAX(FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"MaxDatabaseConnectionsAllowed\"', 'Sum'),0))",
     "metricEditorMode": 1,
     "metricName": "m1",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Client connections [$RDS_Proxy]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 245 },
   "targets": [
    {
     "alias": "ClientConnections_Sum",
     "dimensions": { "ProxyName": "$RDS_Proxy" },
     "expression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"ClientConnections\"', 'Sum'),0)",
     "metricEditorMode": 1,
     "metricName": "ClientConnections",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Server connections [$RDS_Proxy]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 253 },
   "targets": [
    {
     "alias": "DatabaseConnections_Sum",
     "dimensions": { "ProxyName": "$RDS_Proxy" },
     "expression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"DatabaseConnections\"', 'Sum'),0)",
     "metricEditorMode": 1,
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "DatabaseConnectionsCurrentlySessionPinned_Sum",
     "dimensions": { "ProxyName": "$RDS_Proxy" },
     "expression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"DatabaseConnectionsCurrentlySessionPinned\"', 'Sum'),0)",
     "metricEditorMode": 1,
     "metricName": "DatabaseConnectionsCurrentlySessionPinned",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Pinned sessions [$RDS_Proxy]",
   "type": "timeseries",
   "description": "* Your connections to the proxy can enter a state known as `pinning`. When a connection is pinned, each later transaction uses the same underlying database connection until the session ends. Other client connections also can't reuse that database connection until the session ends. The session ends when the client connection is dropped.\n* RDS Proxy automatically pins a client connection to a specific DB connection when it detects a session state change that isn't appropriate for other sessions. `Pinning reduces the effectiveness of connection reuse`. If all or almost all of your connections experience pinning, consider modifying your application code or workload to reduce the conditions that cause the pinning.\n* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy-managing.html#rds-proxy-pinning",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 253 },
   "targets": [
    {
     "alias": "DatabaseConnectionsCurrentlySessionPinned_Sum",
     "dimensions": { "ProxyName": "$RDS_Proxy" },
     "expression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"DatabaseConnectionsCurrentlySessionPinned\"', 'Sum'),0)",
     "metricEditorMode": 1,
     "metricName": "DatabaseConnectionsCurrentlySessionPinned",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Query requests (avg[10s])",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 253 },
   "targets": [
    {
     "alias": "QueryRequests_Average",
     "dimensions": { "ProxyName": "$RDS_Proxy" },
     "expression": "FILL(SEARCH('{AWS/RDS,ProxyName} ProxyName=\"$RDS_Proxy\" MetricName=\"QueryRequests\"', 'Average'),0)",
     "metricEditorMode": 1,
     "metricName": "QueryRequests",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "[WIP] Client connection address - ($RDS_Proxy)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 261 }
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 269 } },
  {
   "title": "Latency (Monolith) - [$RDS_name]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 270 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.95, rate(miro_postgres_query_execution_seconds_bucket[$__rate_interval]))) by(le,name) and on (name) label_replace(label_transform(pg_stat_database_xact_commit{miro_rds_cluster=\"$RDS_name\",datname!~\"(postgres|rdsadmin|template0|template1|)\",namespace=\"observability-exporters\"},\"datname\",\"_\",\"-\"),\"name\",\"$1\",\"datname\",\"(.*)\")",
     "legendFormat": "p95"
    },
    {
     "expr": "max(histogram_quantile(0.99, rate(miro_postgres_query_execution_seconds_bucket[$__rate_interval]))) by(le,name) and on (name) label_replace(label_transform(pg_stat_database_xact_commit{miro_rds_cluster=\"$RDS_name\",datname!~\"(postgres|rdsadmin|template0|template1|)\",namespace=\"observability-exporters\"},\"datname\",\"_\",\"-\"),\"name\",\"$1\",\"datname\",\"(.*)\")",
     "legendFormat": "p99"
    },
    {
     "expr": "max(histogram_quantile(0.999, rate(miro_postgres_query_execution_seconds_bucket[$__rate_interval]))) by(le,name) and on (name) label_replace(label_transform(pg_stat_database_xact_commit{miro_rds_cluster=\"$RDS_name\",datname!~\"(postgres|rdsadmin|template0|template1|)\",namespace=\"observability-exporters\"},\"datname\",\"_\",\"-\"),\"name\",\"$1\",\"datname\",\"(.*)\")",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Long query - [$RDS]",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 270 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /duration:.* ms /\n| parse @message \"duration: * ms\" as duration\n| sort duration desc\n| limit 50\n| display duration, substr(@message, 0, 500)as message",
     "logGroupNames": [
      "/aws/rds/instance/$RDS/postgresql"
     ],
     "queryMode": "Logs",
     "region": "$region"
    }
   ]
  },
  {
   "title": "CPU usage, % [$RDS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 278 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$RDS" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$RDS" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}